# Generated by Django 5.2.9 on 2026-03-23 00:04

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0009_journaldraft_queue_indexes'),
        ('iam', '0003_orgunit_parent_type_name_idx'),
        ('inventarios', '0002_stockmovement_accounting_links'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='InventoryCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='InventoryTaxProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=120)),
                ('tax_treatment', models.CharField(choices=[('GRAVADO', 'Gravado'), ('EXENTO', 'Exento'), ('EXONERADO', 'Exonerado')], default='GRAVADO', max_length=16)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='inventoryitem',
            name='uniq_inv_sku_per_company',
        ),
        migrations.RemoveConstraint(
            model_name='stockbalance',
            name='uniq_inv_balance_per_scope',
        ),
        migrations.RemoveConstraint(
            model_name='stockmovement',
            name='uniq_inv_idempotency_per_company',
        ),
        migrations.RemoveConstraint(
            model_name='warehouse',
            name='uniq_inv_wh_code_per_branch',
        ),
        migrations.RenameIndex(
            model_name='inventoryitem',
            new_name='ix_invitm_c_as',
            old_name='inventarios_company_is_active_sku_idx',
        ),
        migrations.RenameIndex(
            model_name='warehouse',
            new_name='ix_invwh_c_b_an',
            old_name='inventarios_company_branch_is_active_name_idx',
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='allow_discount',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='allow_fraction',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='allow_negative_stock',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='allow_return_to_stock',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='allow_returns',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='alternate_code',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='barcode',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='barcode_type',
            field=models.CharField(blank=True, choices=[('EAN13', 'EAN-13'), ('UPCA', 'UPC-A'), ('CODE128', 'Code 128'), ('INTERNO', 'Interno')], default='', max_length=16),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='controls_stock',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='costing_method',
            field=models.CharField(choices=[('MOVING_WEIGHTED_AVG', 'Moving weighted average')], default='MOVING_WEIGHTED_AVG', max_length=32),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='currency',
            field=models.CharField(default='NIO', max_length=3),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='default_branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inv_items_default_branch', to='iam.orgunit'),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='default_warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='default_for_items', to='inventarios.warehouse'),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='description',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='enabled_branch_ids',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='initial_cost',
            field=models.DecimalField(decimal_places=6, default=Decimal('0.000000'), max_digits=18),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='internal_location',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='invoice_description',
            field=models.CharField(blank=True, default='', max_length=160),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='invoice_name',
            field=models.CharField(blank=True, default='', max_length=160),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='item_type',
            field=models.CharField(choices=[('INVENTARIABLE', 'Inventariable'), ('NO_INVENTARIABLE', 'No inventariable'), ('SERVICIO', 'Servicio')], default='INVENTARIABLE', max_length=20),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='last_known_cost',
            field=models.DecimalField(decimal_places=6, default=Decimal('0.000000'), max_digits=18),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='lead_time_days',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='max_stock',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=18),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='min_qty',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=18),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='min_sale_price',
            field=models.DecimalField(decimal_places=6, default=Decimal('0.000000'), max_digits=18),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='min_stock',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=18),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='preferred_supplier_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='purchase_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='purchase_moq',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=18),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='purchase_multiple',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=18),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='quality_control_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='reorder_point',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=18),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='reorder_qty',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=18),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='reserve_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='rounding_increment',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=18),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='sales_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='search_tags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='shelf_life_days',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='short_name',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='standard_cost',
            field=models.DecimalField(decimal_places=6, default=Decimal('0.000000'), max_digits=18),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='status',
            field=models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo'), ('BLOQUEADO', 'Bloqueado')], default='ACTIVO', max_length=16),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='suggested_price',
            field=models.DecimalField(decimal_places=6, default=Decimal('0.000000'), max_digits=18),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='supplier_item_code',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='tax_treatment',
            field=models.CharField(choices=[('GRAVADO', 'Gravado'), ('EXENTO', 'Exento'), ('EXONERADO', 'Exonerado')], default='GRAVADO', max_length=16),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='transfer_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='uom_base',
            field=models.CharField(choices=[('UNIT', 'Unit'), ('LITER', 'Liter'), ('KILOGRAM', 'Kilogram'), ('BOX', 'Box'), ('GALLON', 'Gallon'), ('METER', 'Meter')], default='UNIT', max_length=16),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='uom_conversions',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='uom_purchase',
            field=models.CharField(choices=[('UNIT', 'Unit'), ('LITER', 'Liter'), ('KILOGRAM', 'Kilogram'), ('BOX', 'Box'), ('GALLON', 'Gallon'), ('METER', 'Meter')], default='UNIT', max_length=16),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='uom_sale',
            field=models.CharField(choices=[('UNIT', 'Unit'), ('LITER', 'Liter'), ('KILOGRAM', 'Kilogram'), ('BOX', 'Box'), ('GALLON', 'Gallon'), ('METER', 'Meter')], default='UNIT', max_length=16),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='use_expiry',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='use_lot',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='use_serial',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='version',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='visible_invoice',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='visible_pos',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='visible_quote',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='uom',
            field=models.CharField(choices=[('UNIT', 'Unit'), ('LITER', 'Liter'), ('KILOGRAM', 'Kilogram'), ('BOX', 'Box'), ('GALLON', 'Gallon'), ('METER', 'Meter')], default='UNIT', max_length=16),
        ),
        migrations.AddIndex(
            model_name='stockbalance',
            index=models.Index(fields=['company', 'branch', 'warehouse', 'item'], name='ix_invbal_scope'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['company', 'branch', 'created_at'], name='ix_invmov_c_b_ca'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['company', 'branch', 'item', 'created_at'], name='ix_invmov_item_ca'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['company', 'branch', 'warehouse', 'created_at'], name='ix_invmov_wh_ca'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['company', 'idempotency_key'], name='ix_invmov_idem'),
        ),
        migrations.AddIndex(
            model_name='warehouse',
            index=models.Index(fields=['company', 'branch', 'code'], name='ix_invwh_c_b_code'),
        ),
        migrations.AddConstraint(
            model_name='stockbalance',
            constraint=models.UniqueConstraint(fields=('company', 'branch', 'warehouse', 'item'), name='uniq_inv_bal_scope'),
        ),
        migrations.AddConstraint(
            model_name='stockmovement',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key', ''), _negated=True), fields=('company', 'idempotency_key'), name='uniq_invmov_idem'),
        ),
        migrations.AddConstraint(
            model_name='warehouse',
            constraint=models.UniqueConstraint(fields=('company', 'branch', 'code'), name='uniq_inv_wh_code_pb'),
        ),
        migrations.AddField(
            model_name='inventorybrand',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inv_brands', to='iam.orgunit'),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='items', to='inventarios.inventorybrand'),
        ),
        migrations.AddField(
            model_name='inventorycategory',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inv_categories', to='iam.orgunit'),
        ),
        migrations.AddField(
            model_name='inventorycategory',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='inventarios.inventorycategory'),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='items', to='inventarios.inventorycategory'),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sub_items', to='inventarios.inventorycategory'),
        ),
        migrations.AddField(
            model_name='inventorytaxprofile',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inv_tax_profiles', to='iam.orgunit'),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='tax_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='items', to='inventarios.inventorytaxprofile'),
        ),
        migrations.AddIndex(
            model_name='inventoryitem',
            index=models.Index(fields=['company', 'is_active', 'name'], name='ix_invitm_c_an'),
        ),
        migrations.AddIndex(
            model_name='inventoryitem',
            index=models.Index(fields=['company', 'barcode'], name='ix_invitm_c_bar'),
        ),
        migrations.AddConstraint(
            model_name='inventoryitem',
            constraint=models.UniqueConstraint(fields=('company', 'sku'), name='uniq_inv_sku_pc'),
        ),
        migrations.AddConstraint(
            model_name='inventoryitem',
            constraint=models.UniqueConstraint(condition=models.Q(('barcode', ''), _negated=True), fields=('company', 'barcode'), name='uniq_inv_barcode_pc'),
        ),
        migrations.AddIndex(
            model_name='inventorybrand',
            index=models.Index(fields=['company', 'is_active', 'name'], name='ix_invbrand_c_an'),
        ),
        migrations.AddConstraint(
            model_name='inventorybrand',
            constraint=models.UniqueConstraint(fields=('company', 'name'), name='uniq_inv_brand_name_c'),
        ),
        migrations.AddIndex(
            model_name='inventorycategory',
            index=models.Index(fields=['company', 'parent', 'is_active', 'name'], name='ix_invcat_c_pan'),
        ),
        migrations.AddConstraint(
            model_name='inventorycategory',
            constraint=models.UniqueConstraint(fields=('company', 'parent', 'name'), name='uniq_inv_cat_name_cp'),
        ),
        migrations.AddIndex(
            model_name='inventorytaxprofile',
            index=models.Index(fields=['company', 'is_active', 'code'], name='ix_invtax_c_ac'),
        ),
        migrations.AddConstraint(
            model_name='inventorytaxprofile',
            constraint=models.UniqueConstraint(fields=('company', 'code'), name='uniq_inv_tax_code_c'),
        ),
    ]
