# Generated by Django 5.2.9 on 2026-03-23 18:08

import decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventarios", "0003_item_master_p0"),
    ]

    operations = [
        migrations.AddField(
            model_name="inventorytaxprofile",
            name="rate",
            field=models.DecimalField(decimal_places=4, default=decimal.Decimal("0.0000"), max_digits=8),
        ),
    ]
