# Generated by Django 5.2.12 on 2026-03-21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sync_engine", "0002_device_request_nonce_and_hmac_secret"),
        ("sync", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="deviceenrollment",
            name="core_device",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="legacy_hmac_enrollment",
                to="sync_engine.device",
            ),
        ),
    ]
