# Generated by Django 5.2.12 on 2026-03-21

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sync_engine", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="device",
            name="hmac_secret_b64",
            field=models.CharField(blank=True, default="", max_length=256),
        ),
        migrations.CreateModel(
            name="DeviceRequestNonce",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("nonce", models.CharField(max_length=128)),
                ("ts", models.BigIntegerField()),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="request_nonces",
                        to="sync_engine.device",
                    ),
                ),
            ],
            options={
                "indexes": [models.Index(fields=["device", "created_at"], name="sync_engine_device__6f5b04_idx")],
                "constraints": [
                    models.UniqueConstraint(fields=("device", "nonce"), name="sync_engine_uniq_device_nonce")
                ],
            },
        ),
    ]
