# Generated by Django 5.2.12 on 2026-05-30 19:47

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hr', '0005_employee_party'),
        ('iam', '0004_rename_iam_orgunit_parent_type_name_idx_iam_orgunit_parent__f0840d_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(help_text='Nombre del turno (ej. Matutino, Nocturno)', max_length=120)),
                ('code', models.CharField(blank=True, default='', max_length=32)),
                ('shift_type', models.CharField(choices=[('FIXED', 'Fixed'), ('ROTATING', 'Rotating'), ('FLEXIBLE', 'Flexible'), ('SPLIT', 'Split')], default='FIXED', max_length=16)),
                ('start_time', models.TimeField(help_text='Hora de inicio del turno')),
                ('end_time', models.TimeField(help_text='Hora de fin del turno')),
                ('break_minutes', models.PositiveIntegerField(default=0, help_text='Minutos de descanso incluidos en el turno')),
                ('late_tolerance_minutes', models.PositiveIntegerField(default=10, help_text='Minutos de tolerancia para llegada tarde')),
                ('early_departure_tolerance_minutes', models.PositiveIntegerField(default=5, help_text='Minutos de tolerancia para salida anticipada')),
                ('is_overnight', models.BooleanField(default=False, help_text='Si el turno cruza medianoche (ej. 22:00 - 06:00)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(blank=True, help_text='Sucursal (opcional, si aplica solo a una sucursal)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='branch_work_shifts', to='iam.orgunit')),
                ('company', models.ForeignKey(help_text='Empresa propietaria del turno', on_delete=django.db.models.deletion.PROTECT, related_name='work_shifts', to='iam.orgunit')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_shifts_created', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('attendance_date', models.DateField(db_index=True, help_text='Fecha de la asistencia')),
                ('check_in', models.DateTimeField(blank=True, help_text='Hora de entrada', null=True)),
                ('check_out', models.DateTimeField(blank=True, help_text='Hora de salida', null=True)),
                ('check_in_method', models.CharField(choices=[('MANUAL', 'Manual'), ('BIOMETRIC', 'Biometric'), ('MOBILE_GPS', 'Mobile GPS'), ('QR_CODE', 'QR Code'), ('SYSTEM', 'System Auto')], default='MANUAL', max_length=16)),
                ('check_out_method', models.CharField(choices=[('MANUAL', 'Manual'), ('BIOMETRIC', 'Biometric'), ('MOBILE_GPS', 'Mobile GPS'), ('QR_CODE', 'QR Code'), ('SYSTEM', 'System Auto')], default='MANUAL', max_length=16)),
                ('status', models.CharField(choices=[('PRESENT', 'Present'), ('ABSENT', 'Absent'), ('LATE', 'Late'), ('HALF_DAY', 'Half Day'), ('ON_LEAVE', 'On Leave'), ('HOLIDAY', 'Holiday')], db_index=True, default='PRESENT', max_length=16)),
                ('worked_hours', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Horas trabajadas calculadas', max_digits=5)),
                ('overtime_hours', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Horas extra', max_digits=5)),
                ('late_minutes', models.PositiveIntegerField(default=0, help_text='Minutos de retraso')),
                ('early_departure_minutes', models.PositiveIntegerField(default=0, help_text='Minutos de salida anticipada')),
                ('check_in_latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('check_in_longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('check_out_latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('check_out_longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('metadata_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendances_approved', to=settings.AUTH_USER_MODEL)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='branch_attendances', to='iam.orgunit')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendances', to='iam.orgunit')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendances_created', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendances', to='hr.employee')),
                ('shift', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendances', to='work_management.workshift')),
            ],
            options={
                'ordering': ['-attendance_date'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('asset_type', models.CharField(choices=[('VEHICLE', 'Vehicle'), ('EQUIPMENT', 'Equipment'), ('FACILITY', 'Facility'), ('OTHER', 'Other')], db_index=True, max_length=16)),
                ('asset_identifier', models.CharField(db_index=True, help_text='Identificador del activo (placa, número de serie, código interno)', max_length=120)),
                ('asset_description', models.CharField(blank=True, default='', help_text='Descripción del activo', max_length=255)),
                ('maintenance_type', models.CharField(choices=[('PREVENTIVE', 'Preventive'), ('CORRECTIVE', 'Corrective'), ('INSPECTION', 'Inspection'), ('EMERGENCY', 'Emergency')], default='INSPECTION', max_length=16)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('NORMAL', 'Normal'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], db_index=True, default='NORMAL', max_length=16)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('IN_REVIEW', 'In Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('COMPLETED', 'Completed')], db_index=True, default='DRAFT', max_length=16)),
                ('title', models.CharField(help_text='Título/resumen del mantenimiento', max_length=255)),
                ('description', models.TextField(help_text='Descripción detallada del trabajo realizado o requerido')),
                ('findings', models.TextField(blank=True, default='', help_text='Hallazgos durante la inspección')),
                ('actions_taken', models.TextField(blank=True, default='', help_text='Acciones realizadas')),
                ('parts_used', models.JSONField(blank=True, default=list, help_text='Lista de partes/repuestos usados [{name, qty, cost}]')),
                ('odometer_reading', models.PositiveIntegerField(blank=True, help_text='Lectura de odómetro (para vehículos)', null=True)),
                ('hours_meter_reading', models.DecimalField(blank=True, decimal_places=2, help_text='Lectura de horómetro (para equipos)', max_digits=10, null=True)),
                ('estimated_cost', models.DecimalField(blank=True, decimal_places=2, help_text='Costo estimado del mantenimiento', max_digits=14, null=True)),
                ('actual_cost', models.DecimalField(blank=True, decimal_places=2, help_text='Costo real del mantenimiento', max_digits=14, null=True)),
                ('scheduled_date', models.DateField(blank=True, help_text='Fecha programada del mantenimiento', null=True)),
                ('started_at', models.DateTimeField(blank=True, help_text='Inicio de ejecución', null=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='Fin de ejecución', null=True)),
                ('next_maintenance_date', models.DateField(blank=True, help_text='Próxima fecha de mantenimiento programado', null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('metadata_json', models.JSONField(blank=True, default=dict)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_logs_approved', to=settings.AUTH_USER_MODEL)),
                ('assigned_to', models.ForeignKey(blank=True, help_text='Empleado asignado para ejecución', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_logs_assigned', to='hr.employee')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='branch_maintenance_logs', to='iam.orgunit')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_logs', to='iam.orgunit')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_logs_created', to=settings.AUTH_USER_MODEL)),
                ('reported_by', models.ForeignKey(help_text='Empleado que reporta/llena la bitácora', on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_logs_reported', to='hr.employee')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['company', 'status', 'priority'], name='work_manage_company_5e0703_idx'), models.Index(fields=['company', 'asset_type', 'asset_identifier'], name='work_manage_company_e77c7e_idx'), models.Index(fields=['reported_by', 'status'], name='work_manage_reporte_27ae75_idx'), models.Index(fields=['assigned_to', 'status'], name='work_manage_assigne_a95c7c_idx'), models.Index(fields=['company', 'branch', 'status'], name='work_manage_company_9a6d21_idx'), models.Index(fields=['scheduled_date'], name='work_manage_schedul_ea5477_idx'), models.Index(fields=['next_maintenance_date'], name='work_manage_next_ma_a786e9_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='workshift',
            index=models.Index(fields=['company', 'is_active'], name='work_manage_company_5b4319_idx'),
        ),
        migrations.AddIndex(
            model_name='workshift',
            index=models.Index(fields=['company', 'branch', 'is_active'], name='work_manage_company_e2d7d5_idx'),
        ),
        migrations.AddConstraint(
            model_name='workshift',
            constraint=models.UniqueConstraint(fields=('company', 'name'), name='uq_workshift_company_name'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['company', 'attendance_date'], name='work_manage_company_657ddf_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['employee', 'attendance_date'], name='work_manage_employe_27eafd_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['company', 'branch', 'attendance_date'], name='work_manage_company_faa69d_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['status', 'attendance_date'], name='work_manage_status_eeaa70_idx'),
        ),
        migrations.AddConstraint(
            model_name='attendance',
            constraint=models.UniqueConstraint(fields=('employee', 'attendance_date'), name='uq_attendance_employee_date'),
        ),
    ]
