from __future__ import annotations

from dataclasses import dataclass

from django.db import transaction

from apps.modulos.rbac.models import Permission, Role, RolePermission


@dataclass(frozen=True)
class SeedResult:
    roles_created: int
    roles_updated: int
    perms_created: int
    perms_updated: int
    roleperms_created: int


def seed_rbac_v01() -> SeedResult:
    """
    Catálogo estándar v0.1 (robusto, modular, extensible).
    - Idempotente (get_or_create + updates)
    - No borra cosas existentes.
    """

    roles = {
        "company_admin": "Administrador global dentro de la empresa (RBAC + ORG + HR + reportes).",
        "branch_manager": "Administrador de sucursal.",
        "hr_manager": "Gestión completa de RRHH.",
        "hr_clerk": "Operación RRHH (altas/bajas/edición), sin RBAC.",
        "auditor": "Lectura de auditoría y reportes.",
        "warehouse_manager": "Gestión de inventario (placeholder).",
        "warehouse_operator": "Operación inventario (placeholder).",
        "sales_manager": "Gestión comercial (placeholder).",
        "sales_rep": "Operación ventas (placeholder).",
        "cashier": "Caja (placeholder).",
        "billing_manager": "Gestión de facturación (kernel).",
        "procurement_manager": "Gestión de compras/procurement (kernel).",
        "sync_admin": "Administración de Sync (enroll/revoke) (placeholder).",

        # FUEL (Estación de Servicios)
        "fuel_admin": "Administrador del módulo Estación de Servicios (todo dentro de la empresa).",
        "fuel_supervisor": "Supervisor Estación (cierres, precios, recibos, conciliaciones).",
        "fuel_cashier": "Cajero/operador Estación (ventas/dispenses; sin precios ni ajustes).",
        "fuel_auditor": "Auditor Estación (solo lectura de operación y reportes).",
        "retail_cashier": "Cajero POS retail.",
        "retail_supervisor": "Supervisor POS retail.",
        "retail_manager": "Administrador POS retail.",
        "retail_auditor": "Auditor POS retail.",
    }

    permissions = {
        # ORG
        "org.company.create": "Crear empresas (COMPANY) bajo el holding",
        "org.company.read": "Ver datos de empresa.",
        "org.company.update": "Actualizar datos de empresa.",
        "org.branch.read": "Ver sucursales.",
        "org.branch.create": "Crear sucursales.",
        "org.branch.update": "Actualizar sucursales.",
        # IAM
        "iam.users.create": "Crear usuarios del sistema (provisionar acceso a empleados).",
        # HR
        "hr.position.read": "Ver puestos.",
        "hr.position.create": "Crear puestos.",
        "hr.position.update": "Actualizar puestos.",
        "hr.position.roles.update": "Actualizar mapeo Puesto->Roles.",
        "hr.employee.read": "Ver empleados.",
        "hr.employee.create": "Crear empleados.",
        "hr.employee.update": "Actualizar empleados.",
        "hr.assignment.read": "Ver asignaciones laborales.",
        "hr.assignment.create": "Crear asignaciones laborales.",
        "hr.assignment.end": "Finalizar asignaciones laborales.",
        # RBAC (para UI admin futura)
        "rbac.roles.read": "Ver roles.",
        "rbac.roles.update": "Actualizar roles.",
        "rbac.permissions.read": "Ver permisos.",
        "rbac.permissions.update": "Actualizar permisos.",
        "rbac.assignments.read": "Ver asignaciones de roles.",
        "rbac.assignments.update": "Actualizar asignaciones de roles.",
        # Auditoría
        "audit.read": "Leer auditoría.",
        "audit.export": "Exportar auditoría.",
        # Reportes
        "report.catalog.read": "Ver catálogo canónico del reporting kernel.",
        "report.dataset.read": "Consultar datasets certificados del reporting kernel.",
        "report.dataset.export": "Exportar datasets certificados del reporting kernel.",
        "report.dashboard.read": "Consumir workspaces publicados del dashboard engine.",
        "report.dashboard.compose": "Componer layouts/widgets de dashboard engine.",
        "report.dashboard.publish": "Publicar workspaces de dashboard engine.",
        "report.dashboard.share": "Compartir workspaces/vistas del dashboard engine.",
        "report.alert.manage": "Gestionar alertas y monitoreo de reportes.",
        "report.snapshot.generate": "Generar snapshots certificados.",
        "report.definition.manage": "Administrar definiciones y semántica del reporting kernel.",
        "reports.definition.read": "Ver definiciones de reportes.",
        "reports.definition.create": "Crear definiciones de reportes.",
        "reports.definition.update": "Actualizar definiciones de reportes.",
        "reports.run.read": "Ver corridas de reportes.",
        "reports.run.create": "Ejecutar corridas de reportes.",
        "reports.snapshot.read": "Ver snapshots de reportes.",
        "reports.audit.read": "Ver auditoría de acceso/ejecución de reportes.",
        "reports.observability.read": "Ver reportes de observabilidad.",
        "reports.financial.read": "Ver reportes financieros certificados.",
        "reports.control.read": "Ver reportes de control/CEC.",
        "reports.security.read": "Ver reportes de seguridad.",
        "reports.trace.read": "Ver reportes de trazabilidad.",
        "reports.admin": "Administrar políticas y gobierno del módulo de reportes.",
        # Dashboard transversal v3
        "dashboard.workspace.read": "Ver catálogo y definición de workspaces del dashboard transversal.",
        "dashboard.widget.read": "Consultar widgets del dashboard transversal.",
        "dashboard.drilldown.read": "Ejecutar drill-down en widgets del dashboard transversal.",
        "dashboard.intercompany.read": "Consultar vistas intercompany del dashboard transversal.",
        # Sync (placeholder)
        "sync.device.enroll": "Enrolar dispositivos.",
        "sync.device.revoke": "Revocar dispositivos.",
        "sync.batch.receive": "Recibir lotes de sync.",
        # --- Inventario (kernels) ---
        "inventory.item.read": "Ver items del inventario.",
        "inventory.item.create": "Crear items del inventario.",
        "inventory.item.update": "Actualizar items del inventario.",
        "inventory.warehouse.create": "Crear almacenes/bodegas.",
        "inventory.balance.read": "Ver existencias y costo promedio.",
        "inventory.movement.receive": "Registrar entradas/recepciones de inventario.",
        "inventory.movement.issue": "Registrar salidas/consumos de inventario.",
        "inventory.movement.adjust": "Registrar ajustes de inventario.",
        "inventory.transfer.create": "Registrar transferencias entre almacenes.",
        "inventory.movement.post": "Registrar/mayorizar movimientos de inventario.",
        "inventory.adjustment.create": "Crear ajustes de inventario.",

        # --- Facturación (kernels) ---
        "billing.customer.read": "Ver clientes.",
        "billing.customer.create": "Crear clientes.",
        "billing.customer.update": "Actualizar clientes.",
        "billing.invoice.read": "Ver facturas.",
        "billing.invoice.create": "Crear facturas (draft).",
        "billing.invoice.issue": "Emitir facturas.",
        "billing.invoice.void": "Anular facturas.",
        "billing.doc.read": "Ver documentos de facturación (kernel).",
        "billing.doc.create": "Crear documentos de facturación (kernel).",
        "billing.doc.issue": "Emitir documentos de facturación (kernel).",
        "billing.doc.void": "Anular documentos de facturación (kernel).",
        "billing.fiscal.config.read": "Ver configuración fiscal por sucursal.",
        "billing.fiscal.config.update": "Actualizar configuración fiscal por sucursal.",
        "billing.doc.print": "Solicitar impresión fiscal de documento.",
        "billing.doc.contingency": "Registrar contingencia fiscal sobre documento.",
        "billing.doc.contingency.resolve": "Resolver contingencia fiscal por reintento o anulación.",
        # --- Payments & Cash (core module) ---
        "payments.intent.read": "Ver intents de pago.",
        "payments.intent.create": "Crear intents de pago.",
        "payments.intent.capture": "Capturar intents de pago.",
        "payments.intent.refund": "Reembolsar intents de pago.",
        "payments.cash_session.read": "Ver sesiones de caja.",
        "payments.cash_session.open": "Abrir sesión de caja.",
        "payments.cash_session.close": "Cerrar sesión de caja.",
        "payments.cash_movement.create": "Registrar movimiento de caja.",
        # --- CEC Control Plane (core module) ---
        "cec.close_run.read": "Ver cierres CEC.",
        "cec.close_run.create": "Crear corridas de cierre CEC.",
        "cec.close_run.update": "Actualizar estado de corridas de cierre CEC.",
        "cec.exception.read": "Ver excepciones CEC.",
        "cec.exception.create": "Crear excepciones CEC.",
        "cec.exception.resolve": "Resolver excepciones CEC.",
        "cec.evidence.create": "Registrar evidencia en CEC.",
        # --- Integration Backbone (core module) ---
        "integration.outbox.read": "Ver outbox canónico.",
        "integration.outbox.publish": "Marcar/publish outbox canónico.",
        "integration.inbox.read": "Ver inbox canónico.",
        "integration.inbox.process": "Procesar/ack inbox canónico.",
        # --- Accounting kernel ---
        "accounting.journal_draft.read": "Ver journal drafts contables.",
        "accounting.journal_draft.approve": "Aprobar journal drafts validados para posting.",
        "accounting.journal_draft.post": "Ejecutar posting de journal drafts a journal entries.",
        "accounting.journal_entry.read": "Ver journal entries posteados.",
        "accounting.journal_entry.reverse": "Generar reversa contable de journal entry.",
        "accounting.journal_entry.reverse_batch": "Ejecutar reversa contable masiva.",
        "accounting.period.read": "Ver periodos fiscales contables.",
        "accounting.period.close": "Cerrar periodo fiscal contable.",
        "accounting.sod.override": "Override excepcional de segregación de funciones en contabilidad.",
        "accounting.coa.read": "Ver catálogo contable (Chart of Accounts).",
        "accounting.coa.update": "Actualizar catálogo contable y configuración GL por compañía.",
        "accounting.fx_rate.read": "Ver tasas FX contables.",
        "accounting.fx_rate.update": "Crear/actualizar tasas FX contables.",
        "accounting.report.read": "Ver reportes financieros formales (Trial Balance, GL, PnL, Balance Sheet).",
        "accounting.dashboard.read": "Ver dashboard ejecutivo contable (KPIs y tendencias).",
        "accounting.revaluation.run": "Ejecutar corrida de revaluación FX.",
        "accounting.intercompany.read": "Ver ciclo intercompany transaccional.",
        "accounting.intercompany.write": "Crear/confirmar/cerrar transacciones intercompany.",
        "accounting.intercompany.reconcile": "Conciliar transacciones intercompany (matching/diferencias/disputa).",
        "accounting.intercompany.dispute": "Abrir disputa formal intercompany.",
        "accounting.intercompany.settle": "Resolver disputa y liquidar/cerrar transacción intercompany.",
        "accounting.consolidation.read": "Ver corridas y reportes de consolidación multi-compañía.",
        "accounting.consolidation.run": "Ejecutar cierre y consolidación financiera multi-compañía.",

        # --- Compat / legacy (tests + transición) ---
        # Nota: se conservan porque varios tests usan estos códigos como canary de RBAC.
        "inventory.read": "Lectura inventario (legacy/compat).",
        "inventory.write": "Escritura inventario (legacy/compat).",
        "clients.read": "Lectura clientes (legacy/compat).",
        "clients.write": "Escritura clientes (legacy/compat).",
        "reports.view": "Ver reportes (legacy/compat).",
        "reports.export": "Exportar reportes (legacy/compat).",

        # FUEL (Estación de Servicios)
        "fuel.config.read": "Leer configuración de estación.",
        "fuel.config.update": "Actualizar configuración de estación.",
        "fuel.shift.open": "Abrir turno.",
        "fuel.shift.close": "Cerrar turno.",
        "fuel.shift.read": "Ver turnos.",
        "fuel.dispense.create": "Registrar despacho (evento físico).",
        "fuel.dispense.read": "Ver despachos (evento físico).",
        "fuel.dispense.void": "Anular despacho.",
        "fuel.sale.create": "Crear venta.",
        "fuel.sale.read": "Ver ventas.",
        "fuel.sale.void": "Anular venta.",
        "fuel.price.read": "Ver precios.",
        "fuel.price.update": "Actualizar precios.",
        "fuel.tank.read": "Ver tanques.",
        "fuel.tank.receive": "Registrar recepción/descarga a tanque.",
        "fuel.tank.adjust": "Registrar ajustes de tanque (merma/derrame/calibración).",
        "fuel.reconcile.view": "Ver conciliaciones y variaciones.",
        "fuel.reconcile.post": "Registrar conciliación.",
        "fuel.outbox.read": "Ver outbox intercompany.",
        "fuel.outbox.reprocess": "Reprocesar outbox intercompany.",
        "fuel.reports.view": "Ver reportes del módulo Estación.",
        "fuel.reports.export": "Exportar reportes del módulo Estación.",
        "fuel.uom_preferences.manage": "Gestionar preferencias UOM de combustible.",
        "retail.pos.use": "Usar la consola POS retail.",
        "retail.ticket.create": "Crear tickets retail.",
        "retail.ticket.update": "Actualizar tickets retail.",
        "retail.ticket.reprice": "Reprecificar o descontar líneas retail.",
        "retail.ticket.hold": "Retener y reanudar tickets retail.",
        "retail.ticket.checkout": "Ejecutar checkout retail.",
        "retail.ticket.void": "Anular ventas retail.",
        "retail.return.create": "Registrar devoluciones retail.",
        "retail.catalog.read": "Consultar catálogo retail POS.",
        "retail.sale.read": "Consultar ventas y devoluciones retail.",
        "retail.shift.close": "Cerrar turno operativo retail.",
        "retail.session.supervise": "Supervisar caja y terminales retail.",
        "retail.compensation.retry": "Reintentar compensaciones retail.",
    }

    permissions.update(
        {
            # INVENTORY kernel (granular)
            "inventory.item.create": "Crear ítems de inventario.",
            "inventory.warehouse.create": "Crear almacenes.",
            "inventory.movement.receive": "Registrar entradas.",
            "inventory.movement.issue": "Registrar salidas.",
            "inventory.movement.adjust": "Registrar ajustes.",
            "inventory.transfer.create": "Registrar transferencias.",
            "inventory.balance.read": "Ver balances.",
            # BILLING kernel
            "billing.doc.create": "Crear documentos (draft).",
            "billing.doc.read": "Ver documentos.",
            "billing.doc.issue": "Emitir documentos.",
            "billing.doc.void": "Anular documentos.",
            # PROCUREMENT kernel
            "procurement.doc.create": "Crear documentos de compra (draft).",
            "procurement.doc.read": "Ver documentos de compra.",
            "procurement.doc.post": "Postear documentos de compra.",
            "procurement.doc.void": "Anular documentos de compra.",
        }
    )

    role_to_perms = {
        "company_admin": [
            "org.company.create",
            "org.company.read",
            "org.company.update",
            "org.branch.read",
            "org.branch.create",
            "org.branch.update",
            "iam.users.create",
            "hr.position.read",
            "hr.position.create",
            "hr.position.update",
            "hr.position.roles.update",
            "hr.employee.read",
            "hr.employee.create",
            "hr.employee.update",
            "hr.assignment.read",
            "hr.assignment.create",
            "hr.assignment.end",
            "rbac.roles.read",
            "rbac.roles.update",
            "rbac.permissions.read",
            "rbac.permissions.update",
            "rbac.assignments.read",
            "rbac.assignments.update",
            "audit.read",
            "audit.export",
            "sync.device.enroll",
            "sync.device.revoke",
            "sync.batch.receive",
            # Inventario (granular)
            "inventory.item.read",
            "inventory.item.create",
            "inventory.item.update",
            "inventory.warehouse.create",
            "inventory.balance.read",
            "inventory.movement.receive",
            "inventory.movement.issue",
            "inventory.movement.adjust",
            "inventory.transfer.create",
            "inventory.movement.post",
            "inventory.adjustment.create",
            # Facturación (granular)
            "billing.customer.read",
            "billing.customer.create",
            "billing.customer.update",
            "billing.invoice.read",
            "billing.invoice.create",
            "billing.invoice.issue",
            "billing.invoice.void",
            "billing.doc.read",
            "billing.doc.create",
            "billing.doc.issue",
            "billing.doc.void",
            "billing.fiscal.config.read",
            "billing.fiscal.config.update",
            "billing.doc.print",
            "billing.doc.contingency",
            "billing.doc.contingency.resolve",
            # Payments/Cash
            "payments.intent.read",
            "payments.intent.create",
            "payments.cash_session.read",
            "payments.cash_session.open",
            "payments.cash_session.close",
            "payments.cash_movement.create",
            # CEC
            "cec.close_run.read",
            "cec.close_run.create",
            "cec.close_run.update",
            "cec.exception.read",
            "cec.exception.create",
            "cec.exception.resolve",
            "cec.evidence.create",
            # Integration backbone
            "integration.outbox.read",
            "integration.outbox.publish",
            "integration.inbox.read",
            "integration.inbox.process",
            # Accounting
            "accounting.journal_draft.read",
            "accounting.journal_draft.approve",
            "accounting.journal_draft.post",
            "accounting.journal_entry.read",
            "accounting.journal_entry.reverse",
            "accounting.journal_entry.reverse_batch",
            "accounting.period.read",
            "accounting.period.close",
            "accounting.sod.override",
            "accounting.coa.read",
            "accounting.coa.update",
            "accounting.fx_rate.read",
            "accounting.fx_rate.update",
            "accounting.report.read",
            "accounting.dashboard.read",
            "accounting.revaluation.run",
            "accounting.intercompany.read",
            "accounting.intercompany.write",
            "accounting.intercompany.reconcile",
            "accounting.intercompany.dispute",
            "accounting.intercompany.settle",
            "accounting.consolidation.read",
            "accounting.consolidation.run",
            # Reportes (kernel)
            "report.catalog.read",
            "report.dataset.read",
            "report.dataset.export",
            "report.dashboard.read",
            "report.dashboard.compose",
            "report.dashboard.publish",
            "report.dashboard.share",
            "report.alert.manage",
            "report.snapshot.generate",
            "report.definition.manage",
            "reports.definition.read",
            "reports.definition.create",
            "reports.definition.update",
            "reports.run.read",
            "reports.run.create",
            "reports.snapshot.read",
            "reports.audit.read",
            "reports.observability.read",
            "reports.financial.read",
            "reports.control.read",
            "reports.security.read",
            "reports.trace.read",
            "reports.admin",
            "dashboard.workspace.read",
            "dashboard.widget.read",
            "dashboard.drilldown.read",
            "dashboard.intercompany.read",
            "reports.export",
            # Compat
            "inventory.read",
            "inventory.write",
            "clients.read",
            "clients.write",
            "reports.view",
            "reports.export",
        ],
        "branch_manager": [
            "org.branch.read",
            "org.branch.update",
            "hr.employee.read",
            "hr.employee.update",
            "hr.assignment.read",
            # Inventario (granular)
            "inventory.item.read",
            "inventory.item.create",
            "inventory.item.update",
            "inventory.warehouse.create",
            "inventory.balance.read",
            "inventory.movement.receive",
            "inventory.movement.issue",
            "inventory.movement.adjust",
            "inventory.transfer.create",
            "inventory.movement.post",
            "inventory.adjustment.create",
            # Facturación (lectura + draft)
            "billing.customer.read",
            "billing.invoice.read",
            "billing.invoice.create",
            "billing.doc.read",
            "billing.doc.create",
            "billing.doc.issue",
            "billing.doc.void",
            "billing.fiscal.config.read",
            "billing.doc.print",
            "billing.doc.contingency",
            "billing.doc.contingency.resolve",
            # Payments/Cash
            "payments.intent.read",
            "payments.intent.create",
            "payments.cash_session.read",
            "payments.cash_session.open",
            "payments.cash_session.close",
            "payments.cash_movement.create",
            # CEC control plane
            "cec.close_run.read",
            "cec.close_run.create",
            "cec.close_run.update",
            "cec.exception.read",
            "cec.exception.create",
            "cec.exception.resolve",
            "cec.evidence.create",
            # Integration backbone (read)
            "integration.outbox.read",
            "integration.inbox.read",
            # Accounting
            "accounting.journal_draft.read",
            "accounting.journal_draft.approve",
            "accounting.journal_draft.post",
            "accounting.journal_entry.read",
            "accounting.journal_entry.reverse",
            "accounting.journal_entry.reverse_batch",
            "accounting.period.read",
            "accounting.coa.read",
            "accounting.fx_rate.read",
            "accounting.report.read",
            "accounting.dashboard.read",
            "accounting.revaluation.run",
            "accounting.intercompany.read",
            "accounting.intercompany.write",
            "accounting.intercompany.reconcile",
            "accounting.intercompany.dispute",
            "accounting.intercompany.settle",
            "accounting.consolidation.read",
            # Reporting kernel (lectura operativa)
            "report.catalog.read",
            "report.dataset.read",
            "report.dataset.export",
            "report.dashboard.read",
            "report.snapshot.generate",
            # Compat
            "inventory.read",
            "inventory.write",
            "clients.read",
            "clients.write",
            "reports.view",
        ],
        "hr_manager": [
            "org.company.read",
            "org.branch.read",
            "iam.users.create",
            "hr.position.read",
            "hr.position.create",
            "hr.position.update",
            "hr.position.roles.update",
            "hr.employee.read",
            "hr.employee.create",
            "hr.employee.update",
            "hr.assignment.read",
            "hr.assignment.create",
            "hr.assignment.end",
        ],
        "hr_clerk": [
            "org.branch.read",
            "hr.position.read",
            "hr.employee.read",
            "hr.employee.create",
            "hr.employee.update",
            "hr.assignment.read",
            "hr.assignment.create",
            "hr.assignment.end",
        ],
        "auditor": [
            "audit.read",
            "reports.view",
            # Reportes (kernel)
            "report.catalog.read",
            "report.dataset.read",
            "report.dataset.export",
            "report.dashboard.read",
            "report.snapshot.generate",
            "reports.definition.read",
            "reports.run.read",
            "reports.snapshot.read",
            "reports.audit.read",
            "reports.observability.read",
            "reports.financial.read",
            "reports.control.read",
            "reports.security.read",
            "reports.trace.read",
            "reports.export",
            "dashboard.workspace.read",
            "dashboard.widget.read",
            "dashboard.drilldown.read",
            "cec.close_run.read",
            "cec.exception.read",
            "integration.outbox.read",
            "integration.inbox.read",
            "accounting.journal_draft.read",
            "accounting.journal_entry.read",
            "accounting.period.read",
            "accounting.coa.read",
            "accounting.fx_rate.read",
            "accounting.report.read",
            "accounting.dashboard.read",
            "accounting.intercompany.read",
            "accounting.consolidation.read",
        ],
        "warehouse_manager": [
            "inventory.item.read",
            "inventory.item.create",
            "inventory.item.update",
            "inventory.movement.post",
            "inventory.adjustment.create",
            # Compat
            "inventory.read",
            "inventory.write",
        ],
        "warehouse_operator": [
            "inventory.item.read",
            "inventory.movement.post",
            # Compat
            "inventory.read",
        ],
        "sales_manager": [
            "billing.customer.read",
            "billing.customer.create",
            "billing.customer.update",
            "billing.invoice.read",
            "billing.invoice.create",
            "billing.invoice.issue",
            "billing.invoice.void",
            # Compat
            "clients.read",
            "clients.write",
            "reports.view",
        ],
        "sales_rep": [
            "billing.customer.read",
            "billing.invoice.read",
            "billing.invoice.create",
            # Compat
            "clients.read",
        ],
        "cashier": [
            "billing.invoice.read",
            "billing.invoice.issue",
            # Compat
            "reports.view",
        ],
        "sync_admin": ["sync.device.enroll", "sync.device.revoke"],

        # FUEL
        "fuel_admin": [
            "fuel.config.read",
            "fuel.config.update",
            "fuel.shift.open",
            "fuel.shift.close",
            "fuel.shift.read",
            "fuel.dispense.create",
            "fuel.dispense.read",
            "fuel.dispense.void",
            "fuel.sale.create",
            "fuel.sale.read",
            "fuel.sale.void",
            "fuel.price.read",
            "fuel.price.update",
            "fuel.tank.read",
            "fuel.tank.receive",
            "fuel.tank.adjust",
            "fuel.reconcile.view",
            "fuel.reconcile.post",
            "fuel.outbox.read",
            "fuel.outbox.reprocess",
            "fuel.reports.view",
            "fuel.reports.export",
            "fuel.uom_preferences.manage",
        ],
        "fuel_supervisor": [
            "fuel.config.read",
            "fuel.shift.open",
            "fuel.shift.close",
            "fuel.shift.read",
            "fuel.dispense.read",
            "fuel.dispense.void",
            "fuel.sale.read",
            "fuel.sale.void",
            "fuel.price.read",
            "fuel.price.update",
            "fuel.tank.read",
            "fuel.tank.receive",
            "fuel.tank.adjust",
            "fuel.reconcile.view",
            "fuel.reconcile.post",
            "fuel.outbox.read",
            "fuel.outbox.reprocess",
            "fuel.reports.view",
            "fuel.reports.export",
            "fuel.uom_preferences.manage",
        ],
        "fuel_cashier": [
            "fuel.shift.open",
            "fuel.shift.read",
            "fuel.dispense.create",
            "fuel.dispense.read",
            "fuel.sale.create",
            "fuel.sale.read",
            "fuel.reports.view",
            "fuel.uom_preferences.manage",
        ],
        "fuel_auditor": [
            "fuel.shift.read",
            "fuel.dispense.read",
            "fuel.sale.read",
            "fuel.price.read",
            "fuel.tank.read",
            "fuel.reconcile.view",
            "fuel.outbox.read",
            "fuel.reports.view",
        ],
        "retail_cashier": [
            "retail.pos.use",
            "retail.ticket.create",
            "retail.ticket.update",
            "retail.ticket.hold",
            "retail.ticket.checkout",
            "retail.catalog.read",
            "retail.sale.read",
            "payments.intent.read",
            "payments.intent.create",
            "payments.cash_session.read",
            "payments.cash_session.open",
            "payments.cash_movement.create",
        ],
        "retail_supervisor": [
            "retail.pos.use",
            "retail.ticket.create",
            "retail.ticket.update",
            "retail.ticket.reprice",
            "retail.ticket.hold",
            "retail.ticket.checkout",
            "retail.ticket.void",
            "retail.return.create",
            "retail.catalog.read",
            "retail.sale.read",
            "retail.shift.close",
            "retail.session.supervise",
            "retail.compensation.retry",
            "payments.intent.read",
            "payments.intent.create",
            "payments.intent.capture",
            "payments.intent.refund",
            "payments.cash_session.read",
            "payments.cash_session.open",
            "payments.cash_session.close",
            "payments.cash_movement.create",
        ],
        "retail_manager": [
            "retail.pos.use",
            "retail.ticket.create",
            "retail.ticket.update",
            "retail.ticket.reprice",
            "retail.ticket.hold",
            "retail.ticket.checkout",
            "retail.ticket.void",
            "retail.return.create",
            "retail.catalog.read",
            "retail.sale.read",
            "retail.shift.close",
            "retail.session.supervise",
            "retail.compensation.retry",
            "billing.doc.read",
            "billing.doc.print",
            "payments.intent.read",
            "payments.intent.create",
            "payments.intent.capture",
            "payments.intent.refund",
            "payments.cash_session.read",
            "payments.cash_session.open",
            "payments.cash_session.close",
            "payments.cash_movement.create",
            "inventory.balance.read",
        ],
        "retail_auditor": [
            "retail.catalog.read",
            "retail.sale.read",
            "payments.intent.read",
            "payments.cash_session.read",
            "billing.doc.read",
            "inventory.balance.read",
            "audit.read",
        ],
    }

    role_to_perms.update(
        {
            "warehouse_manager": [
                "inventory.item.create",
                "inventory.warehouse.create",
                "inventory.movement.receive",
                "inventory.movement.issue",
                "inventory.movement.adjust",
                "inventory.transfer.create",
                "inventory.balance.read",
            ],
            "procurement_manager": [
                "procurement.doc.create",
                "procurement.doc.read",
                "procurement.doc.post",
                "procurement.doc.void",
                "accounting.journal_draft.read",
                "accounting.journal_draft.approve",
                "accounting.journal_draft.post",
                "accounting.journal_entry.read",
                "accounting.report.read",
                "cec.close_run.read",
                "cec.close_run.create",
                "cec.close_run.update",
                "cec.exception.read",
                "cec.exception.resolve",
            ],
            "cashier": [
                "billing.doc.create",
                "billing.doc.read",
                "billing.doc.issue",
                "billing.doc.print",
                "payments.intent.read",
                "payments.intent.create",
                "payments.intent.capture",
                "payments.intent.refund",
                "payments.cash_session.read",
                "payments.cash_session.open",
                "payments.cash_session.close",
                "payments.cash_movement.create",
            ],
            "billing_manager": [
                "billing.doc.create",
                "billing.doc.read",
                "billing.doc.issue",
                "billing.doc.void",
                "billing.fiscal.config.read",
                "billing.fiscal.config.update",
                "billing.doc.print",
                "billing.doc.contingency",
                "billing.doc.contingency.resolve",
                "payments.intent.read",
                "payments.intent.capture",
                "payments.intent.refund",
                "cec.close_run.read",
                "cec.close_run.create",
                "cec.close_run.update",
                "cec.exception.read",
                "cec.exception.resolve",
                "cec.evidence.create",
                "integration.outbox.read",
                "accounting.journal_draft.read",
                "accounting.journal_draft.approve",
                "accounting.journal_draft.post",
                "accounting.journal_entry.read",
                "accounting.journal_entry.reverse",
                "accounting.journal_entry.reverse_batch",
                "accounting.period.read",
                "accounting.sod.override",
                "accounting.coa.read",
                "accounting.coa.update",
                "accounting.fx_rate.read",
                "accounting.fx_rate.update",
                "accounting.report.read",
                "accounting.dashboard.read",
                "accounting.revaluation.run",
                "accounting.intercompany.read",
                "accounting.intercompany.write",
                "accounting.intercompany.reconcile",
                "accounting.intercompany.dispute",
                "accounting.intercompany.settle",
                "accounting.consolidation.read",
                "procurement.doc.create",
                "procurement.doc.read",
                "procurement.doc.post",
                "procurement.doc.void",
            ],
        }
    )

    for role_name in ("company_admin",):
        codes = role_to_perms.get(role_name, [])
        for code in (
            "procurement.doc.create",
            "procurement.doc.read",
            "procurement.doc.post",
            "procurement.doc.void",
            "payments.intent.capture",
            "payments.intent.refund",
            "retail.pos.use",
            "retail.ticket.create",
            "retail.ticket.update",
            "retail.ticket.reprice",
            "retail.ticket.hold",
            "retail.ticket.checkout",
            "retail.ticket.void",
            "retail.return.create",
            "retail.catalog.read",
            "retail.sale.read",
            "retail.shift.close",
            "retail.session.supervise",
            "retail.compensation.retry",
        ):
            if code not in codes:
                codes.append(code)

    roles_created = roles_updated = perms_created = perms_updated = roleperms_created = 0

    with transaction.atomic():
        role_objs: dict[str, Role] = {}
        for name, desc in roles.items():
            role_obj, created = Role.objects.get_or_create(
                name=name,
                defaults={"description": desc, "is_active": True},
            )
            if created:
                roles_created += 1
            else:
                role_update_fields: list[str] = []
                if role_obj.description != desc:
                    role_obj.description = desc
                    role_update_fields.append("description")
                if not role_obj.is_active:
                    role_obj.is_active = True
                    role_update_fields.append("is_active")
                if role_update_fields:
                    role_obj.save(update_fields=role_update_fields)
                    roles_updated += 1
            role_objs[name] = role_obj

        perm_objs: dict[str, Permission] = {}
        for code, desc in permissions.items():
            perm_obj, created = Permission.objects.get_or_create(
                code=code, defaults={"description": desc, "is_active": True}
            )
            if created:
                perms_created += 1
            else:
                perm_update_fields: list[str] = []
                if perm_obj.description != desc:
                    perm_obj.description = desc
                    perm_update_fields.append("description")
                if not perm_obj.is_active:
                    perm_obj.is_active = True
                    perm_update_fields.append("is_active")
                if perm_update_fields:
                    perm_obj.save(update_fields=perm_update_fields)
                    perms_updated += 1
            perm_objs[code] = perm_obj

        for role_name, perm_codes in role_to_perms.items():
            role = role_objs[role_name]
            for code in perm_codes:
                perm = perm_objs.get(code)
                if perm is None:
                    # Catálogo inconsistente => fallo duro
                    raise ValueError(f"Permiso no existe en seed permissions: {code}")
                _, rp_created = RolePermission.objects.get_or_create(role=role, permission=perm)
                if rp_created:
                    roleperms_created += 1
    return SeedResult(
        roles_created=roles_created,
        roles_updated=roles_updated,
        perms_created=perms_created,
        perms_updated=perms_updated,
        roleperms_created=roleperms_created,
    )
