# Generated by Django 5.2.9 on 2025-12-31 21:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditChainHead",
            fields=[
                ("id", models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ("last_event_hash", models.CharField(blank=True, default="", max_length=64)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="AuditChainHeadV2",
            fields=[
                ("partition_key", models.CharField(max_length=64, primary_key=True, serialize=False)),
                ("last_event_hash", models.CharField(blank=True, default="", max_length=64)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="AuditEvent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("event_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("schema_version", models.PositiveSmallIntegerField(default=1)),
                ("module", models.CharField(default="AUTH", max_length=32)),
                ("event_type", models.CharField(max_length=64)),
                ("reason_code", models.CharField(blank=True, default="", max_length=64)),
                ("subject_type", models.CharField(blank=True, default="", max_length=32)),
                ("subject_id", models.CharField(blank=True, default="", max_length=128)),
                ("partition_key", models.CharField(blank=True, db_index=True, default="", max_length=64)),
                ("timestamp_server", models.DateTimeField()),
                ("device_id", models.CharField(blank=True, default="", max_length=64)),
                ("ip_server_seen", models.GenericIPAddressField(blank=True, null=True)),
                ("offline_mode", models.BooleanField(default=False)),
                ("user_agent", models.TextField(blank=True, default="")),
                ("path", models.CharField(blank=True, default="", max_length=256)),
                ("method", models.CharField(blank=True, default="", max_length=16)),
                ("before_snapshot", models.JSONField(blank=True, default=dict)),
                ("after_snapshot", models.JSONField(blank=True, default=dict)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("prev_event_hash", models.CharField(blank=True, default="", max_length=64)),
                ("event_hash", models.CharField(blank=True, max_length=64, null=True)),
                ("signature", models.CharField(blank=True, max_length=64, null=True)),
                (
                    "actor_user",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["timestamp_server"], name="audit_audit_timesta_ca7846_idx"),
                    models.Index(fields=["module", "event_type"], name="audit_audit_module_729abe_idx"),
                    models.Index(fields=["actor_user", "timestamp_server"], name="audit_audit_actor_u_e4376d_idx"),
                    models.Index(fields=["subject_type", "subject_id"], name="audit_audit_subject_b49148_idx"),
                    models.Index(fields=["partition_key", "-timestamp_server"], name="audit_pk_ts_idx"),
                    models.Index(
                        fields=["partition_key", "event_type", "-timestamp_server"], name="audit_pk_type_ts_idx"
                    ),
                    models.Index(
                        fields=["partition_key", "reason_code", "-timestamp_server"], name="audit_pk_reason_ts_idx"
                    ),
                ],
            },
        ),
    ]
