from __future__ import annotations

from django.urls import path

from .views import (
    BalanceSheetReportView,
    ChartOfAccountView,
    ConsolidationBalanceSheetReportView,
    ConsolidationPnLReportView,
    ConsolidationRunSummaryView,
    ConsolidationRunView,
    ConsolidationTrialBalanceReportView,
    FiscalPeriodCloseView,
    FiscalPeriodListView,
    FxRateUpsertView,
    FxRevaluationRunView,
    GeneralLedgerReportView,
    HealthView,
    IntercompanyTransactionCloseView,
    IntercompanyTransactionConfirmView,
    IntercompanyTransactionDisputeView,
    IntercompanyTransactionListCreateView,
    IntercompanyTransactionReconcileView,
    IntercompanyTransactionSettleView,
    IntercompanyDisputeReasonListView,
    IntercompanyDisputeCaseListView,
    IntercompanyDisputeCaseReviewView,
    JournalDraftApproveView,
    JournalDraftListView,
    JournalDraftPostView,
    JournalEntryListView,
    JournalEntryReverseBatchView,
    JournalEntryReverseView,
    OperationalReconciliationReportView,
    PnLReportView,
    TrialBalanceReportView,
)


urlpatterns = [
    path("health/", HealthView.as_view()),
    path("journal-drafts/", JournalDraftListView.as_view()),
    path("journal-drafts/approve/", JournalDraftApproveView.as_view()),
    path("journal-drafts/post/", JournalDraftPostView.as_view()),
    path("journal-entries/", JournalEntryListView.as_view()),
    path("journal-entries/reverse-batch/", JournalEntryReverseBatchView.as_view()),
    path("journal-entries/<int:entry_id>/reverse/", JournalEntryReverseView.as_view()),
    path("periods/", FiscalPeriodListView.as_view()),
    path("periods/close/", FiscalPeriodCloseView.as_view()),
    path("chart-of-accounts/", ChartOfAccountView.as_view()),
    path("reports/trial-balance/", TrialBalanceReportView.as_view()),
    path("reports/general-ledger/", GeneralLedgerReportView.as_view()),
    path("reports/pnl/", PnLReportView.as_view()),
    path("reports/balance-sheet/", BalanceSheetReportView.as_view()),
    path("reports/operational-reconciliation/", OperationalReconciliationReportView.as_view()),
    path("fx-rates/", FxRateUpsertView.as_view()),
    path("revaluation/run/", FxRevaluationRunView.as_view()),
    path("intercompany/transactions/", IntercompanyTransactionListCreateView.as_view()),
    path("intercompany/transactions/<str:tx_id>/confirm/", IntercompanyTransactionConfirmView.as_view()),
    path("intercompany/transactions/<str:tx_id>/reconcile/", IntercompanyTransactionReconcileView.as_view()),
    path("intercompany/transactions/<str:tx_id>/dispute/", IntercompanyTransactionDisputeView.as_view()),
    path("intercompany/transactions/<str:tx_id>/settle/", IntercompanyTransactionSettleView.as_view()),
    path("intercompany/transactions/<str:tx_id>/close/", IntercompanyTransactionCloseView.as_view()),
    path("intercompany/dispute-reasons/", IntercompanyDisputeReasonListView.as_view()),
    path("intercompany/disputes/", IntercompanyDisputeCaseListView.as_view()),
    path("intercompany/disputes/<str:case_id>/review/", IntercompanyDisputeCaseReviewView.as_view()),
    path("consolidation/run/", ConsolidationRunView.as_view()),
    path("consolidation/runs/<str:run_id>/summary/", ConsolidationRunSummaryView.as_view()),
    path("consolidation/reports/trial-balance/", ConsolidationTrialBalanceReportView.as_view()),
    path("consolidation/reports/pnl/", ConsolidationPnLReportView.as_view()),
    path("consolidation/reports/balance-sheet/", ConsolidationBalanceSheetReportView.as_view()),
]
