# Generated by Codex on 2026-05-28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parties", "0001_initial"),
        ("retail_pos", "0004_posticket_ck_pos_ticket_comp_pending_state_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="posticket",
            name="customer_party",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="pos_tickets",
                to="parties.party",
            ),
        ),
        migrations.AddIndex(
            model_name="posticket",
            index=models.Index(fields=["company", "customer_party"], name="ix_pos_ticket_co_cust_party"),
        ),
    ]
