# Generated by Django 5.2.9 on 2026-03-07

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("iam", "0003_orgunit_parent_type_name_idx"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CloseRun",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("run_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                (
                    "run_type",
                    models.CharField(
                        choices=[("DAILY", "Daily"), ("PERIODIC", "Periodic")],
                        default="DAILY",
                        max_length=16,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("CREATED", "Created"),
                            ("GATHERED", "Gathered"),
                            ("VALIDATED", "Validated"),
                            ("PACKAGED", "Packaged"),
                            ("DELIVERED", "Delivered"),
                            ("REOPENED_EXCEPTION", "Reopened exception"),
                        ],
                        default="CREATED",
                        max_length=24,
                    ),
                ),
                ("started_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("input_manifest_hash", models.CharField(blank=True, default="", max_length=64)),
                ("output_manifest_hash", models.CharField(blank=True, default="", max_length=64)),
                ("summary_json", models.JSONField(default=dict)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cec_close_runs_branch",
                        to="iam.orgunit",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cec_close_runs_company",
                        to="iam.orgunit",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cec_close_runs_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CECException",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("exception_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("source_module", models.CharField(max_length=64)),
                ("code", models.CharField(max_length=64)),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("LOW", "Low"),
                            ("MEDIUM", "Medium"),
                            ("HIGH", "High"),
                            ("CRITICAL", "Critical"),
                        ],
                        default="MEDIUM",
                        max_length=12,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPEN", "Open"),
                            ("IN_PROGRESS", "In progress"),
                            ("RESOLVED", "Resolved"),
                            ("CLOSED", "Closed"),
                        ],
                        default="OPEN",
                        max_length=16,
                    ),
                ),
                ("related_object_type", models.CharField(blank=True, default="", max_length=64)),
                ("related_object_id", models.CharField(blank=True, default="", max_length=64)),
                ("details_json", models.JSONField(default=dict)),
                ("opened_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("resolution_note", models.TextField(blank=True, default="")),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cec_exceptions_assigned",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cec_exceptions_branch",
                        to="iam.orgunit",
                    ),
                ),
                (
                    "close_run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="exceptions",
                        to="cec.closerun",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cec_exceptions_company",
                        to="iam.orgunit",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EvidenceArtifact",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("artifact_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("support_id", models.CharField(max_length=96, unique=True)),
                ("sha256", models.CharField(max_length=64)),
                ("mime_type", models.CharField(max_length=64)),
                ("storage_ref", models.CharField(max_length=255)),
                ("metadata_json", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                (
                    "close_run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="artifacts",
                        to="cec.closerun",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="closerun",
            index=models.Index(
                fields=["company", "branch", "run_type", "status", "started_at"],
                name="cec_closeru_company_d4469f_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="cecexception",
            index=models.Index(fields=["status", "severity", "opened_at"], name="cec_cecexc_status_826f17_idx"),
        ),
        migrations.AddIndex(
            model_name="cecexception",
            index=models.Index(fields=["company", "branch", "status"], name="cec_cecexc_company_e8f12c_idx"),
        ),
        migrations.AddIndex(
            model_name="evidenceartifact",
            index=models.Index(fields=["close_run", "created_at"], name="cec_evidenc_close_r_b93cf2_idx"),
        ),
    ]
