# Generated by Django 5.2.9 on 2026-05-27 02:30

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('iam', '0004_rename_iam_orgunit_parent_type_name_idx_iam_orgunit_parent__f0840d_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('party_type', models.CharField(choices=[('NATURAL', 'Natural'), ('JURIDICAL', 'Juridical'), ('INTERNAL', 'Internal')], max_length=16)),
                ('display_name', models.CharField(max_length=200)),
                ('legal_name', models.CharField(blank=True, default='', max_length=255)),
                ('tax_id', models.CharField(blank=True, default='', max_length=64)),
                ('national_id', models.CharField(blank=True, default='', max_length=64)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('phone', models.CharField(blank=True, default='', max_length=64)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('BLOCKED', 'Blocked')], default='ACTIVE', max_length=16)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='parties', to='iam.orgunit')),
            ],
        ),
        migrations.CreateModel(
            name='PartyRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('CUSTOMER', 'Customer'), ('SUPPLIER', 'Supplier'), ('EMPLOYEE', 'Employee'), ('PRODUCER', 'Producer'), ('DECLARANT', 'Declarant'), ('EXTERNAL_BUYER', 'External buyer')], max_length=32)),
                ('is_active', models.BooleanField(default=True)),
                ('valid_from', models.DateTimeField(default=django.utils.timezone.now)),
                ('valid_to', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='parties.party')),
            ],
        ),
        migrations.AddIndex(
            model_name='party',
            index=models.Index(fields=['company', 'status', 'display_name'], name='ix_party_company_status_name'),
        ),
        migrations.AddIndex(
            model_name='party',
            index=models.Index(fields=['company', 'tax_id'], name='ix_party_company_tax_id'),
        ),
        migrations.AddIndex(
            model_name='party',
            index=models.Index(fields=['company', 'national_id'], name='ix_party_company_nat_id'),
        ),
        migrations.AddConstraint(
            model_name='party',
            constraint=models.UniqueConstraint(condition=models.Q(('tax_id', ''), _negated=True), fields=('company', 'tax_id'), name='uq_party_company_tax_id'),
        ),
        migrations.AddConstraint(
            model_name='party',
            constraint=models.UniqueConstraint(condition=models.Q(('national_id', ''), _negated=True), fields=('company', 'national_id'), name='uq_party_company_national_id'),
        ),
        migrations.AddIndex(
            model_name='partyrole',
            index=models.Index(fields=['party', 'is_active'], name='ix_partyrole_party_active'),
        ),
        migrations.AddIndex(
            model_name='partyrole',
            index=models.Index(fields=['party', 'role', 'is_active'], name='ix_partyrole_party_role_active'),
        ),
        migrations.AddIndex(
            model_name='partyrole',
            index=models.Index(fields=['role', 'is_active'], name='ix_partyrole_role_active'),
        ),
        migrations.AddConstraint(
            model_name='partyrole',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('party', 'role'), name='uq_party_role_active'),
        ),
    ]
