# Generated by Django 5.2.9 on 2026-03-08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cec", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cecexception",
            name="fingerprint",
            field=models.CharField(blank=True, db_index=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="cecexception",
            name="is_blocking",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="closerun",
            name="blocking_exceptions_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="closerun",
            name="consistency_score",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="closerun",
            name="window_end",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="closerun",
            name="window_start",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name="closerun",
            index=models.Index(
                fields=["company", "branch", "window_start", "window_end"],
                name="cec_closeru_company_2a5de2_idx",
            ),
        ),
    ]
