# Generated by Django 5.2.9 on 2026-01-28

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies: list[tuple[str, str]] = []

    operations = [
        migrations.CreateModel(
            name="DeviceEnrollment",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("device_name", models.CharField(blank=True, default="", max_length=120)),
                ("secret_b64", models.CharField(max_length=256)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="AppliedCommand",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("command_id", models.UUIDField()),
                ("command_type", models.CharField(max_length=64)),
                ("request_hash", models.CharField(max_length=64)),
                ("status", models.CharField(max_length=32)),
                ("response_json", models.JSONField()),
                ("applied_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="applied_commands",
                        to="sync.deviceenrollment",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["device", "applied_at"], name="ix_apcmd_dev_at"),
                    models.Index(fields=["command_type", "applied_at"], name="ix_apcmd_type_at"),
                ],
                "constraints": [
                    models.UniqueConstraint(fields=("device", "command_id"), name="uniq_device_command"),
                ],
            },
        ),
        migrations.CreateModel(
            name="DeviceRequestNonce",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("nonce", models.CharField(max_length=128)),
                ("ts", models.BigIntegerField()),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nonces",
                        to="sync.deviceenrollment",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["device", "created_at"], name="ix_drnonce_dev_ca"),
                ],
                "constraints": [
                    models.UniqueConstraint(fields=("device", "nonce"), name="uniq_device_nonce"),
                ],
            },
        ),
    ]
