# Generated by Django 5.2.9 on 2026-01-02 22:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hr", "0001_initial"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="positionrolemap",
            name="hr_positionrolemap_position_isactive_idx",
        ),
        migrations.RenameIndex(
            model_name="employee",
            new_name="hr_employee_company_77ce24_idx",
            old_name="hr_employee_company_isactive_idx",
        ),
        migrations.RenameIndex(
            model_name="employee",
            new_name="hr_employee_linked__09e1af_idx",
            old_name="hr_employee_linked_user_idx",
        ),
        migrations.RenameIndex(
            model_name="employmentassignment",
            new_name="hr_employme_employe_9af615_idx",
            old_name="hr_employmentassignment_employee_isactive_idx",
        ),
        migrations.RenameIndex(
            model_name="employmentassignment",
            new_name="hr_employme_positio_69a5fc_idx",
            old_name="hr_employmentassignment_position_isactive_idx",
        ),
        migrations.RenameIndex(
            model_name="employmentassignment",
            new_name="hr_employme_branch__0e1c22_idx",
            old_name="hr_employmentassignment_branch_isactive_idx",
        ),
        migrations.RenameIndex(
            model_name="jobposition",
            new_name="hr_jobposit_company_36cec3_idx",
            old_name="hr_jobposition_company_isactive_idx",
        ),
        migrations.AlterField(
            model_name="employee",
            name="id",
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
        ),
        migrations.AlterField(
            model_name="employmentassignment",
            name="id",
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
        ),
        migrations.AlterField(
            model_name="jobposition",
            name="id",
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
        ),
        migrations.AlterField(
            model_name="positionrolemap",
            name="id",
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
        ),
        migrations.AlterField(
            model_name="positionrolemap",
            name="scope_mode",
            field=models.CharField(
                choices=[("COMPANY", "Company"), ("BRANCH", "Branch")], default="BRANCH", max_length=16
            ),
        ),
    ]
