# Generated by Django 5.2.9 on 2026-03-23 18:08

import decimal
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("facturacion", "0005_bill_number_unique_nonzero"),
        ("iam", "0003_orgunit_parent_type_name_idx"),
        ("inventarios", "0004_tax_profile_rate"),
        ("payments", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RetailBranchConfig",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("series", models.CharField(default="RTL", max_length=16)),
                ("price_includes_tax", models.BooleanField(default=False)),
                ("hold_expiry_minutes", models.PositiveIntegerField(default=120)),
                ("print_after_issue", models.BooleanField(default=False)),
                ("require_customer_for_fiscal", models.BooleanField(default=False)),
                ("allow_manual_reprice", models.BooleanField(default=False)),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "branch",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="retail_branch_config",
                        to="iam.orgunit",
                    ),
                ),
                (
                    "default_warehouse",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="retail_branch_configs",
                        to="inventarios.warehouse",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RetailTerminal",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("code", models.CharField(max_length=32)),
                ("name", models.CharField(max_length=120)),
                ("device_ref", models.CharField(blank=True, default="", max_length=96)),
                ("receipt_printer_ref", models.CharField(blank=True, default="", max_length=96)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="retail_terminals",
                        to="iam.orgunit",
                    ),
                ),
            ],
            options={
                "indexes": [models.Index(fields=["branch", "is_active", "code"], name="ventas_retai_branch__1565ae_idx")],
                "constraints": [
                    models.UniqueConstraint(fields=("branch", "code"), name="uq_retail_terminal_branch_code"),
                ],
            },
        ),
        migrations.CreateModel(
            name="RetailTicket",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "ticket_kind",
                    models.CharField(
                        choices=[("SALE", "Sale"), ("RETURN", "Return")],
                        default="SALE",
                        max_length=16,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("OPEN", "Open"),
                            ("PAID", "Paid"),
                            ("CLOSED", "Closed"),
                            ("VOIDED", "Voided"),
                        ],
                        default="DRAFT",
                        max_length=16,
                    ),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("UNPAID", "Unpaid"),
                            ("INTENDED", "Intended"),
                            ("CAPTURED", "Captured"),
                            ("PARTIAL", "Partial"),
                            ("REFUNDED", "Refunded"),
                            ("FAILED", "Failed"),
                        ],
                        default="UNPAID",
                        max_length=16,
                    ),
                ),
                (
                    "fulfillment_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("STOCK_APPLIED", "Stock applied"),
                            ("REVERSED", "Reversed"),
                        ],
                        default="PENDING",
                        max_length=24,
                    ),
                ),
                (
                    "compensation_status",
                    models.CharField(
                        choices=[
                            ("NONE", "None"),
                            ("COMPENSATING", "Compensating"),
                            ("FAILED", "Failed"),
                        ],
                        default="NONE",
                        max_length=24,
                    ),
                ),
                ("version", models.PositiveIntegerField(default=1)),
                ("flow_correlation_id", models.CharField(blank=True, db_index=True, default="", max_length=96)),
                ("checkout_lock_token", models.CharField(blank=True, default="", max_length=96)),
                ("customer_name", models.CharField(blank=True, default="", max_length=200)),
                ("customer_ref", models.CharField(blank=True, default="", max_length=96)),
                ("subtotal", models.DecimalField(decimal_places=2, default=decimal.Decimal("0.00"), max_digits=18)),
                ("tax_total", models.DecimalField(decimal_places=2, default=decimal.Decimal("0.00"), max_digits=18)),
                ("discount_total", models.DecimalField(decimal_places=2, default=decimal.Decimal("0.00"), max_digits=18)),
                ("total", models.DecimalField(decimal_places=2, default=decimal.Decimal("0.00"), max_digits=18)),
                ("last_error", models.CharField(blank=True, default="", max_length=255)),
                ("compensation_attempts", models.PositiveIntegerField(default=0)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "billing_doc",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="retail_tickets",
                        to="facturacion.billingdocument",
                    ),
                ),
                (
                    "cash_session",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="retail_tickets",
                        to="payments.cashsession",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="retail_tickets_company",
                        to="iam.orgunit",
                    ),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="retail_tickets_branch",
                        to="iam.orgunit",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="retail_tickets_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "payment_intent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="retail_tickets",
                        to="payments.paymentintent",
                    ),
                ),
                (
                    "terminal",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tickets",
                        to="ventas_retail.retailterminal",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["company", "branch", "status", "created_at"], name="ventas_retai_company_c0b15c_idx"),
                    models.Index(fields=["branch", "ticket_kind", "status", "created_at"], name="ventas_retai_branch__a24a9d_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="RetailTicketLine",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("source_line_id", models.PositiveIntegerField(blank=True, null=True)),
                ("position", models.PositiveIntegerField(default=1)),
                ("sku_snapshot", models.CharField(max_length=64)),
                ("name_snapshot", models.CharField(max_length=160)),
                ("invoice_name_snapshot", models.CharField(blank=True, default="", max_length=160)),
                ("uom_snapshot", models.CharField(default="UNIT", max_length=16)),
                ("tax_profile_snapshot", models.CharField(blank=True, default="", max_length=64)),
                ("tax_rate_snapshot", models.DecimalField(decimal_places=4, default=decimal.Decimal("0.0000"), max_digits=8)),
                ("qty", models.DecimalField(decimal_places=4, max_digits=18)),
                ("unit_price", models.DecimalField(decimal_places=6, max_digits=18)),
                ("discount_amount", models.DecimalField(decimal_places=2, default=decimal.Decimal("0.00"), max_digits=18)),
                ("line_subtotal", models.DecimalField(decimal_places=2, default=decimal.Decimal("0.00"), max_digits=18)),
                ("line_tax", models.DecimalField(decimal_places=2, default=decimal.Decimal("0.00"), max_digits=18)),
                ("line_total", models.DecimalField(decimal_places=2, default=decimal.Decimal("0.00"), max_digits=18)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "inventory_item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="retail_ticket_lines",
                        to="inventarios.inventoryitem",
                    ),
                ),
                (
                    "ticket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="ventas_retail.retailticket",
                    ),
                ),
            ],
            options={
                "indexes": [models.Index(fields=["ticket", "position"], name="ventas_retai_ticket__99d144_idx")],
                "constraints": [
                    models.UniqueConstraint(fields=("ticket", "position"), name="uq_retail_ticket_line_position"),
                ],
            },
        ),
        migrations.CreateModel(
            name="RetailSale",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "inventory_movement_ids",
                    models.JSONField(blank=True, default=list),
                ),
                ("reversal_movement_ids", models.JSONField(blank=True, default=list)),
                ("flow_correlation_id", models.CharField(blank=True, db_index=True, default="", max_length=96)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("CHECKOUT_PENDING", "Checkout pending"),
                            ("COMPLETED", "Completed"),
                            ("VOIDED", "Voided"),
                            ("COMPENSATING", "Compensating"),
                            ("COMPENSATION_FAILED", "Compensation failed"),
                        ],
                        default="CHECKOUT_PENDING",
                        max_length=32,
                    ),
                ),
                ("accounting_status", models.CharField(blank=True, default="", max_length=24)),
                ("compensation_attempts", models.PositiveIntegerField(default=0)),
                ("compensation_last_error", models.CharField(blank=True, default="", max_length=255)),
                ("compensation_next_retry_at", models.DateTimeField(blank=True, null=True)),
                ("voided_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "billing_doc",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="retail_sales",
                        to="facturacion.billingdocument",
                    ),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="retail_sales_branch",
                        to="iam.orgunit",
                    ),
                ),
                (
                    "cash_movement",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="retail_sales",
                        to="payments.cashmovement",
                    ),
                ),
                (
                    "cash_session",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="retail_sales",
                        to="payments.cashsession",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="retail_sales_company",
                        to="iam.orgunit",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="retail_sales_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "payment_intent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="retail_sales",
                        to="payments.paymentintent",
                    ),
                ),
                (
                    "terminal",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sales",
                        to="ventas_retail.retailterminal",
                    ),
                ),
                (
                    "ticket",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sale",
                        to="ventas_retail.retailticket",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["company", "branch", "status", "created_at"], name="ventas_retai_company_7c8d7d_idx"),
                    models.Index(fields=["status", "compensation_next_retry_at", "created_at"], name="ventas_retai_status_5365da_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="RetailPaymentRecord",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "kind",
                    models.CharField(
                        choices=[("SALE_CAPTURE", "Sale capture"), ("SALE_REFUND", "Sale refund")],
                        max_length=24,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("INTENDED", "Intended"),
                            ("CAPTURED", "Captured"),
                            ("REFUNDED", "Refunded"),
                            ("FAILED", "Failed"),
                        ],
                        default="INTENDED",
                        max_length=16,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=18)),
                ("cash_received", models.DecimalField(decimal_places=2, default=decimal.Decimal("0.00"), max_digits=18)),
                ("change_due", models.DecimalField(decimal_places=2, default=decimal.Decimal("0.00"), max_digits=18)),
                ("reason", models.CharField(blank=True, default="", max_length=255)),
                ("idempotency_key", models.CharField(blank=True, default="", max_length=96)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                (
                    "cash_movement",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="retail_payment_records",
                        to="payments.cashmovement",
                    ),
                ),
                (
                    "payment_intent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="retail_payment_records",
                        to="payments.paymentintent",
                    ),
                ),
                (
                    "ticket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_records",
                        to="ventas_retail.retailticket",
                    ),
                ),
            ],
            options={
                "indexes": [models.Index(fields=["ticket", "kind", "created_at"], name="ventas_retai_ticket__9c748c_idx")],
                "constraints": [
                    models.UniqueConstraint(
                        condition=~models.Q(idempotency_key=""),
                        fields=("ticket", "kind", "idempotency_key"),
                        name="uq_retail_payment_record_ticket_kind_idem",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="RetailHold",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("RESUMED", "Resumed"),
                            ("CANCELLED", "Cancelled"),
                            ("EXPIRED", "Expired"),
                        ],
                        default="ACTIVE",
                        max_length=16,
                    ),
                ),
                ("reason", models.CharField(blank=True, default="", max_length=255)),
                ("held_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("resumed_at", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                (
                    "held_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="retail_holds_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "ticket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="holds",
                        to="ventas_retail.retailticket",
                    ),
                ),
            ],
            options={
                "indexes": [models.Index(fields=["status", "expires_at", "held_at"], name="ventas_retai_status_0925f3_idx")],
            },
        ),
        migrations.CreateModel(
            name="RetailReturn",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("inventory_movement_ids", models.JSONField(blank=True, default=list)),
                ("flow_correlation_id", models.CharField(blank=True, db_index=True, default="", max_length=96)),
                ("idempotency_key", models.CharField(blank=True, default="", max_length=96)),
                (
                    "status",
                    models.CharField(
                        choices=[("CREATED", "Created"), ("COMPLETED", "Completed"), ("FAILED", "Failed")],
                        default="CREATED",
                        max_length=16,
                    ),
                ),
                ("reason", models.CharField(blank=True, default="", max_length=255)),
                ("refund_amount", models.DecimalField(decimal_places=2, default=decimal.Decimal("0.00"), max_digits=18)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="retail_returns_branch",
                        to="iam.orgunit",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="retail_returns_company",
                        to="iam.orgunit",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="retail_returns_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "credit_note_doc",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="retail_returns",
                        to="facturacion.billingdocument",
                    ),
                ),
                (
                    "original_sale",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="returns",
                        to="ventas_retail.retailsale",
                    ),
                ),
                (
                    "refund_cash_movement",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="retail_returns",
                        to="payments.cashmovement",
                    ),
                ),
                (
                    "refund_payment_intent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="retail_returns",
                        to="payments.paymentintent",
                    ),
                ),
                (
                    "return_ticket",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="return_record",
                        to="ventas_retail.retailticket",
                    ),
                ),
            ],
            options={
                "indexes": [models.Index(fields=["company", "branch", "status", "created_at"], name="ventas_retai_company_720cff_idx")],
                "constraints": [
                    models.UniqueConstraint(
                        condition=~models.Q(idempotency_key=""),
                        fields=("company", "idempotency_key"),
                        name="uq_retail_return_company_idempotency",
                    ),
                ],
            },
        ),
    ]
