# Generated by Django 5.2.9 on 2026-03-23 19:05

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("iam", "0003_orgunit_parent_type_name_idx"),
        ("ventas_retail", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RetailCommandExecution",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("CHECKOUT_COMMIT", "Checkout commit"),
                            ("SALE_VOID", "Sale void"),
                            ("RETURN_CREATE", "Return create"),
                            ("COMPENSATION_RETRY", "Compensation retry"),
                        ],
                        max_length=32,
                    ),
                ),
                ("idempotency_key", models.CharField(max_length=96)),
                ("request_hash", models.CharField(max_length=64)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("STARTED", "Started"),
                            ("SUCCEEDED", "Succeeded"),
                            ("FAILED", "Failed"),
                        ],
                        default="STARTED",
                        max_length=16,
                    ),
                ),
                ("response_json", models.JSONField(blank=True, default=dict)),
                ("error_json", models.JSONField(blank=True, default=dict)),
                ("correlation_id", models.CharField(blank=True, default="", max_length=96)),
                ("causation_id", models.CharField(blank=True, default="", max_length=96)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="retail_command_exec_branch",
                        to="iam.orgunit",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="retail_command_exec_company",
                        to="iam.orgunit",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["company", "branch", "action", "created_at"],
                        name="ventas_retai_company_6d8f0a_idx",
                    ),
                    models.Index(fields=["status", "created_at"], name="ventas_retai_status_20cf76_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("company", "action", "idempotency_key"),
                        name="uq_retail_cmd_exec_company_action_idem",
                    ),
                ],
            },
        ),
    ]
