# Generated by Django 5.2.9 on 2025-12-27 20:46

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrgUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_type', models.CharField(choices=[('HOLDING', 'Holding'), ('COMPANY', 'Company'), ('BRANCH', 'Branch')], max_length=16)),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(blank=True, default='', max_length=64)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='iam.orgunit')),
            ],
        ),
        migrations.CreateModel(
            name='OrgClosure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depth', models.PositiveIntegerField()),
                ('ancestor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='closure_ancestor', to='iam.orgunit')),
                ('descendant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='closure_descendant', to='iam.orgunit')),
            ],
        ),
        migrations.CreateModel(
            name='AdminGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capability', models.CharField(choices=[('MANAGE_USERS', 'Manage users'), ('MANAGE_ROLE_ASSIGNMENTS', 'Manage role assignments'), ('VIEW_REPORTS', 'View reports'), ('VIEW_AUDIT', 'View audit')], max_length=64)),
                ('applies_to_subtree', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('granted_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_grants_given', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_grants', to=settings.AUTH_USER_MODEL)),
                ('org_unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='admin_grants', to='iam.orgunit')),
            ],
        ),
        migrations.CreateModel(
            name='UserMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('joined_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('left_at', models.DateTimeField(blank=True, null=True)),
                ('org_unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='memberships', to='iam.orgunit')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='orgunit',
            index=models.Index(fields=['unit_type', 'is_active'], name='iam_orgunit_unit_ty_53ff9d_idx'),
        ),
        migrations.AddIndex(
            model_name='orgunit',
            index=models.Index(fields=['parent', 'unit_type'], name='iam_orgunit_parent__4604b8_idx'),
        ),
        migrations.AddIndex(
            model_name='orgclosure',
            index=models.Index(fields=['ancestor', 'depth'], name='iam_orgclos_ancesto_7009a8_idx'),
        ),
        migrations.AddIndex(
            model_name='orgclosure',
            index=models.Index(fields=['descendant', 'depth'], name='iam_orgclos_descend_5542b3_idx'),
        ),
        migrations.AddConstraint(
            model_name='orgclosure',
            constraint=models.UniqueConstraint(fields=('ancestor', 'descendant'), name='uq_orgclosure_ancestor_descendant'),
        ),
        migrations.AddIndex(
            model_name='admingrant',
            index=models.Index(fields=['user', 'is_active'], name='iam_admingr_user_id_be0fb7_idx'),
        ),
        migrations.AddIndex(
            model_name='admingrant',
            index=models.Index(fields=['org_unit', 'capability'], name='iam_admingr_org_uni_ad05be_idx'),
        ),
        migrations.AddConstraint(
            model_name='admingrant',
            constraint=models.UniqueConstraint(fields=('user', 'org_unit', 'capability'), name='uq_admingrant_user_org_cap'),
        ),
        migrations.AddIndex(
            model_name='usermembership',
            index=models.Index(fields=['user', 'is_active'], name='iam_usermem_user_id_db3e1e_idx'),
        ),
        migrations.AddIndex(
            model_name='usermembership',
            index=models.Index(fields=['org_unit', 'is_active'], name='iam_usermem_org_uni_a32c3e_idx'),
        ),
        migrations.AddConstraint(
            model_name='usermembership',
            constraint=models.UniqueConstraint(fields=('user', 'org_unit'), name='uq_membership_user_orgunit'),
        ),
    ]
