# Generated by Django 5.2.9 on 2025-12-29 22:29

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iam', '0001_initial'),
        ('rbac', '0002_roleassignment'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_type', models.CharField(choices=[('HOLDING', 'Holding'), ('ALLIANCE', 'Alliance'), ('FRANCHISE', 'Franchise'), ('SUPPLIER', 'Supplier'), ('CORPORATE_CLIENT', 'Corporate client')], default='ALLIANCE', max_length=32)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=16)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_company_links', to='iam.orgunit')),
                ('to_company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incoming_company_links', to='iam.orgunit')),
            ],
        ),
        migrations.CreateModel(
            name='LinkGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_mode', models.CharField(choices=[('READ', 'Read'), ('WRITE', 'Write')], default='READ', max_length=8)),
                ('is_active', models.BooleanField(default=True)),
                ('valid_from', models.DateTimeField(blank=True, null=True)),
                ('valid_to', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grants', to='iam.companylink')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='intercompany_grants', to='rbac.permission')),
                ('scope_org_unit', models.ForeignKey(blank=True, help_text='NULL => toda from_company; no-NULL => BRANCH de from_company.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='intercompany_grant_scopes', to='iam.orgunit')),
            ],
        ),
        migrations.AddIndex(
            model_name='companylink',
            index=models.Index(fields=['from_company', 'status', 'is_active'], name='iam_company_from_co_aff22f_idx'),
        ),
        migrations.AddIndex(
            model_name='companylink',
            index=models.Index(fields=['to_company', 'status', 'is_active'], name='iam_company_to_comp_037c57_idx'),
        ),
        migrations.AddConstraint(
            model_name='companylink',
            constraint=models.UniqueConstraint(fields=('from_company', 'to_company'), name='uq_companylink_from_to'),
        ),
        migrations.AddIndex(
            model_name='linkgrant',
            index=models.Index(fields=['is_active', 'access_mode'], name='iam_linkgra_is_acti_2fdc2e_idx'),
        ),
        migrations.AddIndex(
            model_name='linkgrant',
            index=models.Index(fields=['permission', 'access_mode'], name='iam_linkgra_permiss_b9b2f3_idx'),
        ),
        migrations.AddIndex(
            model_name='linkgrant',
            index=models.Index(fields=['scope_org_unit'], name='iam_linkgra_scope_o_16091d_idx'),
        ),
        migrations.AddConstraint(
            model_name='linkgrant',
            constraint=models.UniqueConstraint(fields=('link', 'permission', 'access_mode', 'scope_org_unit'), name='uq_linkgrant_link_perm_mode_scope'),
        ),
    ]
