# Generated by Django 5.2.9 on 2025-12-31 21:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('iam', '0001_initial'),
        ('rbac', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='linkgrant',
            name='permission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='intercompany_grants', to='rbac.permission'),
        ),
        migrations.AddField(
            model_name='orgunit',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='iam.orgunit'),
        ),
        migrations.AddField(
            model_name='orgclosure',
            name='ancestor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='closure_ancestor', to='iam.orgunit'),
        ),
        migrations.AddField(
            model_name='orgclosure',
            name='descendant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='closure_descendant', to='iam.orgunit'),
        ),
        migrations.AddField(
            model_name='linkgrant',
            name='scope_org_unit',
            field=models.ForeignKey(blank=True, help_text='NULL => toda from_company; no-NULL => BRANCH de from_company.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='intercompany_grant_scopes', to='iam.orgunit'),
        ),
        migrations.AddField(
            model_name='companylink',
            name='from_company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_company_links', to='iam.orgunit'),
        ),
        migrations.AddField(
            model_name='companylink',
            name='to_company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incoming_company_links', to='iam.orgunit'),
        ),
        migrations.AddField(
            model_name='admingrant',
            name='org_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='admin_grants', to='iam.orgunit'),
        ),
        migrations.AddField(
            model_name='usermembership',
            name='org_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='memberships', to='iam.orgunit'),
        ),
        migrations.AddField(
            model_name='usermembership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='orgunit',
            index=models.Index(fields=['unit_type', 'is_active'], name='iam_orgunit_unit_ty_53ff9d_idx'),
        ),
        migrations.AddIndex(
            model_name='orgunit',
            index=models.Index(fields=['parent', 'unit_type'], name='iam_orgunit_parent__4604b8_idx'),
        ),
        migrations.AddIndex(
            model_name='orgclosure',
            index=models.Index(fields=['ancestor', 'depth'], name='iam_orgclos_ancesto_7009a8_idx'),
        ),
        migrations.AddIndex(
            model_name='orgclosure',
            index=models.Index(fields=['descendant', 'depth'], name='iam_orgclos_descend_5542b3_idx'),
        ),
        migrations.AddConstraint(
            model_name='orgclosure',
            constraint=models.UniqueConstraint(fields=('ancestor', 'descendant'), name='uq_orgclosure_ancestor_descendant'),
        ),
        migrations.AddIndex(
            model_name='linkgrant',
            index=models.Index(fields=['is_active', 'access_mode'], name='iam_linkgra_is_acti_2fdc2e_idx'),
        ),
        migrations.AddIndex(
            model_name='linkgrant',
            index=models.Index(fields=['permission', 'access_mode'], name='iam_linkgra_permiss_b9b2f3_idx'),
        ),
        migrations.AddIndex(
            model_name='linkgrant',
            index=models.Index(fields=['scope_org_unit'], name='iam_linkgra_scope_o_16091d_idx'),
        ),
        migrations.AddConstraint(
            model_name='linkgrant',
            constraint=models.UniqueConstraint(fields=('link', 'permission', 'access_mode', 'scope_org_unit'), name='uq_linkgrant_link_perm_mode_scope'),
        ),
        migrations.AddIndex(
            model_name='companylink',
            index=models.Index(fields=['from_company', 'status', 'is_active'], name='iam_company_from_co_aff22f_idx'),
        ),
        migrations.AddIndex(
            model_name='companylink',
            index=models.Index(fields=['to_company', 'status', 'is_active'], name='iam_company_to_comp_037c57_idx'),
        ),
        migrations.AddConstraint(
            model_name='companylink',
            constraint=models.UniqueConstraint(fields=('from_company', 'to_company'), name='uq_companylink_from_to'),
        ),
        migrations.AddIndex(
            model_name='admingrant',
            index=models.Index(fields=['user', 'is_active'], name='iam_admingr_user_id_be0fb7_idx'),
        ),
        migrations.AddIndex(
            model_name='admingrant',
            index=models.Index(fields=['org_unit', 'capability'], name='iam_admingr_org_uni_ad05be_idx'),
        ),
        migrations.AddConstraint(
            model_name='admingrant',
            constraint=models.UniqueConstraint(fields=('user', 'org_unit', 'capability'), name='uq_admingrant_user_org_cap'),
        ),
        migrations.AddIndex(
            model_name='usermembership',
            index=models.Index(fields=['user', 'is_active'], name='iam_usermem_user_id_db3e1e_idx'),
        ),
        migrations.AddIndex(
            model_name='usermembership',
            index=models.Index(fields=['org_unit', 'is_active'], name='iam_usermem_org_uni_a32c3e_idx'),
        ),
        migrations.AddConstraint(
            model_name='usermembership',
            constraint=models.UniqueConstraint(fields=('user', 'org_unit'), name='uq_membership_user_orgunit'),
        ),
    ]
