export const BUSINESS_LABELS = {
  humanResources: 'Recursos Humanos',
  organization: 'Organizacion',
  accounting: 'Contabilidad',
  inventory: 'Inventario',
  accessControl: 'Control de Acceso',
  rolesAndPermissions: 'Roles y Permisos',
  identityAndAccess: 'Identidad y Acceso',
  fuel: 'Combustible',
  retail: 'Ventas',
  synchronization: 'Sincronizacion',
  analytics: 'Analitica',
} as const;

export const UI_ROUTE_PATHS = {
  dashboard: '/dashboard',
  analyticsV3: '/analitica/v3',
  accountingDashboard: '/contabilidad/tablero',
  inventoryDashboard: '/inventario',
  inventoryItems: '/inventario/items',
  inventoryItemNew: '/inventario/items/nuevo',
  inventoryItemEdit: '/inventario/items/:id/editar',
  inventoryWarehouses: '/inventario/almacenes',
  inventoryMovements: '/inventario/movimientos',
  inventoryBalances: '/inventario/balances',
  inventoryKardex: '/inventario/kardex',
  selectContext: '/select-context',
  organizationCompanies: '/organizacion/empresas',
  organizationCompanyProfile: '/organizacion/perfil-empresa',
  organizationBranches: '/organizacion/sucursales',
  humanResourcesPositions: '/recursos-humanos/puestos',
  humanResourcesEmployees: '/recursos-humanos/empleados',
  fuelDashboard: '/combustible',
  fuelHealth: '/combustible/salud',
  retailPos: '/ventas',
  auditLog: '/audit/bitacora',
  synchronizationEnrollment: '/sincronizacion/enrolamiento',
  synchronizationDevices: '/sincronizacion/dispositivos',
} as const;

export const LEGACY_ROUTE_PATHS = {
  organizationCompanies: '/backend/org/companies',
  organizationCompanyProfile: '/backend/org/company-profile',
  organizationBranches: '/backend/org/branches',
  humanResourcesPositions: '/hr/positions',
  humanResourcesEmployees: '/hr/employees',
  fuelDashboard: '/fuel',
  fuelHealth: '/fuel/health',
  retailPos: '/retail',
  inventoryDashboard: '/inventory',
  inventoryItems: '/inventory/items',
  inventoryWarehouses: '/inventory/warehouses',
  inventoryMovements: '/inventory/movements',
  inventoryBalances: '/inventory/balances',
  inventoryKardex: '/inventory/kardex',
  synchronizationEnrollment: '/sync/enrollment',
  synchronizationDevices: '/sync/devices',
} as const;
