export const BUSINESS_LABELS = {
  humanResources: 'Recursos Humanos',
  organization: 'Organizacion',
  accessControl: 'Control de Acceso',
  rolesAndPermissions: 'Roles y Permisos',
  identityAndAccess: 'Identidad y Acceso',
  fuel: 'Combustible',
  retailPos: 'Retail POS',
  inventory: 'Inventarios',
  analytics: 'Analytics',
  synchronization: 'Sincronizacion',
} as const;

export const UI_ROUTE_PATHS = {
  dashboard: '/dashboard',
  selectContext: '/select-context',
  organizationCompanies: '/organizacion/empresas',
  organizationCompanyProfile: '/organizacion/perfil-empresa',
  organizationBranches: '/organizacion/sucursales',
  humanResourcesPositions: '/recursos-humanos/puestos',
  humanResourcesEmployees: '/recursos-humanos/empleados',
  fuelDashboard: '/combustible',
  fuelHealth: '/combustible/salud',
  retailPosTerminal: '/retail/pos/terminal',
  retailPosCockpit: '/retail/pos/cockpit',
  inventory: '/inventarios',
  analytics: '/analytics',
  auditLog: '/audit/bitacora',
  synchronizationEnrollment: '/sincronizacion/enrolamiento',
  synchronizationDevices: '/sincronizacion/dispositivos',
} as const;

export const LEGACY_ROUTE_PATHS = {
  organizationCompanies: '/org/companies',
  organizationCompanyProfile: '/org/company-profile',
  organizationBranches: '/org/branches',
  humanResourcesPositions: '/hr/positions',
  humanResourcesEmployees: '/hr/employees',
  fuelDashboard: '/fuel',
  fuelHealth: '/fuel/health',
  retailPosTerminal: '/pos/terminal',
  retailPosCockpit: '/pos/cockpit',
  analytics: '/analytics',
  synchronizationEnrollment: '/sync/enrollment',
  synchronizationDevices: '/sync/devices',
} as const;
