# Generated by Django 5.2.9 on 2026-01-02 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0002_roleassignment_origin'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='roleassignment',
            new_name='rbac_roleas_origin_7700cc_idx',
            old_name='rbac_roleas_origin_isactive_idx',
        ),
    ]
