# Generated by Django 5.2.9 on 2026-03-07

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("iam", "0003_orgunit_parent_type_name_idx"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OutboxEvent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("event_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("source_module", models.CharField(max_length=64)),
                ("event_type", models.CharField(max_length=128)),
                ("schema_version", models.PositiveSmallIntegerField(default=1)),
                ("device_id", models.CharField(blank=True, default="", max_length=96)),
                ("correlation_id", models.CharField(blank=True, default="", max_length=96)),
                ("causation_id", models.CharField(blank=True, default="", max_length=96)),
                ("payload", models.JSONField(default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[("PENDING", "Pending"), ("SENT", "Sent"), ("FAILED", "Failed")],
                        default="PENDING",
                        max_length=16,
                    ),
                ),
                ("attempt_count", models.PositiveIntegerField(default=0)),
                ("last_error", models.CharField(blank=True, default="", max_length=255)),
                ("occurred_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                (
                    "actor_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="outbox_events_actor",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="outbox_events_branch",
                        to="iam.orgunit",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="outbox_events_company",
                        to="iam.orgunit",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="InboxEvent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("event_id", models.UUIDField()),
                ("consumer", models.CharField(max_length=64)),
                ("source_module", models.CharField(blank=True, default="", max_length=64)),
                ("event_type", models.CharField(max_length=128)),
                ("schema_version", models.PositiveSmallIntegerField(default=1)),
                ("payload", models.JSONField(default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[("RECEIVED", "Received"), ("PROCESSED", "Processed"), ("FAILED", "Failed")],
                        default="RECEIVED",
                        max_length=16,
                    ),
                ),
                ("last_error", models.CharField(blank=True, default="", max_length=255)),
                ("received_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AddConstraint(
            model_name="inboxevent",
            constraint=models.UniqueConstraint(fields=("event_id", "consumer"), name="uq_inbox_event_consumer"),
        ),
        migrations.AddIndex(
            model_name="outboxevent",
            index=models.Index(fields=["status", "occurred_at"], name="integratio_status_43d458_idx"),
        ),
        migrations.AddIndex(
            model_name="outboxevent",
            index=models.Index(
                fields=["source_module", "event_type", "occurred_at"],
                name="integratio_source__7f8f5f_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="inboxevent",
            index=models.Index(fields=["consumer", "status", "received_at"], name="integratio_consume_6ab9e4_idx"),
        ),
    ]
