# Generated by Django 5.2.9 on 2026-03-08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("integration", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="outboxevent",
            name="next_attempt_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name="outboxevent",
            index=models.Index(fields=["status", "next_attempt_at"], name="integratio_status_3ec52d_idx"),
        ),
    ]
