# Generated by Django 5.2.9 on 2026-01-02 00:00

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("iam", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CompanyProfile",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("legal_name", models.CharField(max_length=255, blank=True, default="")),
                ("tax_id", models.CharField(max_length=64, blank=True, default="")),
                ("address", models.TextField(blank=True, default="")),
                ("phone", models.CharField(max_length=64, blank=True, default="")),
                ("email", models.EmailField(blank=True, default="")),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, related_name="company_profile", to="iam.orgunit"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BranchProfile",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("address", models.TextField(blank=True, default="")),
                ("phone", models.CharField(max_length=64, blank=True, default="")),
                ("email", models.EmailField(blank=True, default="")),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "branch",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, related_name="branch_profile", to="iam.orgunit"
                    ),
                ),
            ],
        ),
    ]
