# Generated by Django 5.2.12 on 2026-05-27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parties", "0001_initial"),
        ("hr", "0004_rename_hr_employassign_emp_active_start_idx_hr_employme_employe_4b785a_idx"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="party",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="employee_records",
                to="parties.party",
            ),
        ),
        migrations.AddIndex(
            model_name="employee",
            index=models.Index(fields=["company", "party"], name="hr_employee_company_party_idx"),
        ),
    ]
