# Generated by Django 5.2.9 on 2026-03-18 16:15

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iam', '0003_orgunit_parent_type_name_idx'),
        ('reports', '0002_code_charfield'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DatasetCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cache_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('dataset_code', models.CharField(max_length=64)),
                ('dataset_version', models.CharField(max_length=32)),
                ('scope_hash', models.CharField(max_length=64)),
                ('params_hash', models.CharField(max_length=64)),
                ('source_manifest_hash', models.CharField(blank=True, default='', max_length=64)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('expires_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DatasetVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataset_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('dataset_code', models.CharField(max_length=64)),
                ('dataset_version', models.CharField(max_length=32)),
                ('source_registry_refs', models.JSONField(blank=True, default=list)),
                ('shape_contract', models.JSONField(blank=True, default=dict)),
                ('join_contract', models.JSONField(blank=True, default=dict)),
                ('privacy_contract', models.JSONField(blank=True, default=dict)),
                ('quality_contract', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReportExport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('export_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('format', models.CharField(default='json', max_length=16)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('READY', 'Ready'), ('FAILED', 'Failed'), ('BLOCKED', 'Blocked'), ('PENDING_APPROVAL', 'Pending Approval')], default='PENDING', max_length=24)),
                ('template_version', models.CharField(default='v1', max_length=32)),
                ('watermark_text', models.CharField(blank=True, default='', max_length=300)),
                ('requested_reason', models.CharField(blank=True, default='', max_length=300)),
                ('download_scope', models.JSONField(blank=True, default=dict)),
                ('retention_until', models.DateTimeField(blank=True, null=True)),
                ('audit_event_ref', models.CharField(blank=True, default='', max_length=64)),
                ('storage_ref', models.CharField(blank=True, default='', max_length=300)),
                ('content', models.JSONField(blank=True, default=dict)),
                ('content_hash', models.CharField(blank=True, default='', max_length=64)),
                ('error', models.CharField(blank=True, default='', max_length=500)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('exported_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReportReadAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_audit_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('branch_id', models.IntegerField(blank=True, null=True)),
                ('action', models.CharField(choices=[('READ', 'Read'), ('EXPORT', 'Export')], default='READ', max_length=16)),
                ('report_code', models.CharField(max_length=64)),
                ('scope', models.JSONField(blank=True, default=dict)),
                ('sensitivity_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('restricted', 'Restricted')], default='medium', max_length=16)),
                ('reason', models.CharField(blank=True, default='', max_length=300)),
                ('request_id', models.CharField(blank=True, default='', max_length=64)),
                ('ip_server_seen', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReproducibilityLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ledger_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('report_code', models.CharField(max_length=64)),
                ('report_version', models.CharField(max_length=32)),
                ('formula_version', models.CharField(blank=True, default='', max_length=64)),
                ('dataset_version', models.CharField(blank=True, default='', max_length=64)),
                ('effective_scope', models.JSONField(blank=True, default=dict)),
                ('as_of', models.DateTimeField(blank=True, null=True)),
                ('time_window', models.JSONField(blank=True, default=dict)),
                ('input_manifest_hash', models.CharField(max_length=64)),
                ('output_manifest_hash', models.CharField(max_length=64)),
                ('signature', models.CharField(blank=True, default='', max_length=128)),
                ('verification_status', models.CharField(choices=[('VERIFIED', 'Verified'), ('MISMATCH', 'Mismatch'), ('PENDING', 'Pending')], default='PENDING', max_length=16)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SourceRegistry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('source_code', models.CharField(max_length=64)),
                ('source_type', models.CharField(choices=[('DOMAIN_EVENTS', 'Domain Events'), ('AUDIT_EVENTS', 'Audit Events'), ('SYSTEM_LOGS', 'System Logs'), ('METRICS', 'Metrics'), ('SYNC_EVENTS', 'Sync Events'), ('SECURITY_EVENTS', 'Security Events'), ('CERTIFIED_SNAPSHOTS', 'Certified Snapshots'), ('READ_MODELS', 'Read Models')], max_length=32)),
                ('producer_module', models.CharField(max_length=64)),
                ('contract_version', models.CharField(default='1.0.0', max_length=32)),
                ('schema_version', models.PositiveIntegerField(default=1)),
                ('truth_level', models.CharField(choices=[('operational', 'Operational'), ('audit_control', 'Audit Control'), ('observability', 'Observability'), ('certified_financial', 'Certified Financial')], default='operational', max_length=32)),
                ('supports_scope', models.BooleanField(default=True)),
                ('supports_request_id', models.BooleanField(default=True)),
                ('supports_correlation', models.BooleanField(default=False)),
                ('supports_replay', models.BooleanField(default=False)),
                ('scope_fields', models.JSONField(blank=True, default=list)),
                ('correlation_fields', models.JSONField(blank=True, default=list)),
                ('event_types', models.JSONField(blank=True, default=list)),
                ('pii_policy', models.CharField(default='none', max_length=32)),
                ('retention_policy', models.CharField(default='short_term', max_length=32)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('DEPRECATED', 'Deprecated'), ('DISABLED', 'Disabled')], default='ACTIVE', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='reportdefinition',
            name='allow_intercompany',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reportdefinition',
            name='classification',
            field=models.CharField(default='internal', max_length=32),
        ),
        migrations.AddField(
            model_name='reportdefinition',
            name='contains_pii',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reportdefinition',
            name='dataset_version',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='reportdefinition',
            name='deprecated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reportdefinition',
            name='export_policy',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='reportdefinition',
            name='filter_contract',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='reportdefinition',
            name='formula_version',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='reportdefinition',
            name='freshness_class',
            field=models.CharField(default='live', max_length=32),
        ),
        migrations.AddField(
            model_name='reportdefinition',
            name='input_contracts',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='reportdefinition',
            name='max_pending_jobs',
            field=models.PositiveIntegerField(default=20),
        ),
        migrations.AddField(
            model_name='reportdefinition',
            name='max_rows',
            field=models.PositiveIntegerField(default=5000),
        ),
        migrations.AddField(
            model_name='reportdefinition',
            name='max_window_days',
            field=models.PositiveIntegerField(default=31),
        ),
        migrations.AddField(
            model_name='reportdefinition',
            name='output_schema',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='reportdefinition',
            name='owner_domain',
            field=models.CharField(default='REPORTS', max_length=64),
        ),
        migrations.AddField(
            model_name='reportdefinition',
            name='reason_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reportdefinition',
            name='replacement_report_code',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='reportdefinition',
            name='report_family',
            field=models.CharField(choices=[('TRACE', 'Trace'), ('AUDIT', 'Audit'), ('OPS', 'Ops'), ('OBS', 'Obs'), ('CONTROL', 'Control'), ('FIN', 'Fin'), ('SEC', 'Sec')], default='TRACE', max_length=16),
        ),
        migrations.AddField(
            model_name='reportdefinition',
            name='reproducibility_mode',
            field=models.CharField(choices=[('LIVE', 'Live'), ('SNAPSHOT', 'Snapshot'), ('CERTIFIED', 'Certified')], default='LIVE', max_length=16),
        ),
        migrations.AddField(
            model_name='reportdefinition',
            name='retention_policy',
            field=models.CharField(default='short_term', max_length=32),
        ),
        migrations.AddField(
            model_name='reportdefinition',
            name='sensitivity_level',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('restricted', 'Restricted')], default='medium', max_length=16),
        ),
        migrations.AddField(
            model_name='reportdefinition',
            name='source_types',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='reportdefinition',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('DEPRECATED', 'Deprecated'), ('DISABLED', 'Disabled')], default='ACTIVE', max_length=16),
        ),
        migrations.AddField(
            model_name='reportdefinition',
            name='supports_async_snapshot',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reportdefinition',
            name='supports_future_modules',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='reportdefinition',
            name='truth_level',
            field=models.CharField(choices=[('operational', 'Operational'), ('audit_control', 'Audit Control'), ('observability', 'Observability'), ('certified_financial', 'Certified Financial')], default='operational', max_length=32),
        ),
        migrations.AddField(
            model_name='reportdefinition',
            name='version',
            field=models.CharField(default='1.0.0', max_length=32),
        ),
        migrations.AddField(
            model_name='reportrun',
            name='as_of',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reportrun',
            name='classification',
            field=models.CharField(default='internal', max_length=32),
        ),
        migrations.AddField(
            model_name='reportrun',
            name='dataset_version',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='reportrun',
            name='dedupe_key',
            field=models.CharField(blank=True, default='', max_length=96),
        ),
        migrations.AddField(
            model_name='reportrun',
            name='duration_ms',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reportrun',
            name='effective_scope',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='reportrun',
            name='error_code',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='reportrun',
            name='error_envelope',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='reportrun',
            name='formula_version',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='reportrun',
            name='freshness',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='reportrun',
            name='is_async',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reportrun',
            name='output_manifest_hash',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='reportrun',
            name='params_hash',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='reportrun',
            name='priority',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='reportrun',
            name='queue_name',
            field=models.CharField(default='default', max_length=32),
        ),
        migrations.AddField(
            model_name='reportrun',
            name='report_version',
            field=models.CharField(default='1.0.0', max_length=32),
        ),
        migrations.AddField(
            model_name='reportrun',
            name='reproducibility_mode',
            field=models.CharField(choices=[('LIVE', 'Live'), ('SNAPSHOT', 'Snapshot'), ('CERTIFIED', 'Certified')], default='LIVE', max_length=16),
        ),
        migrations.AddField(
            model_name='reportrun',
            name='row_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reportrun',
            name='sensitivity_level',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('restricted', 'Restricted')], default='medium', max_length=16),
        ),
        migrations.AddField(
            model_name='reportrun',
            name='source_manifest',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='reportrun',
            name='source_manifest_hash',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='reportrun',
            name='source_types',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='reportrun',
            name='time_window',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='reportrun',
            name='truth_level',
            field=models.CharField(choices=[('operational', 'Operational'), ('audit_control', 'Audit Control'), ('observability', 'Observability'), ('certified_financial', 'Certified Financial')], default='operational', max_length=32),
        ),
        migrations.AddField(
            model_name='reportrun',
            name='warnings',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='reportrun',
            name='status',
            field=models.CharField(choices=[('QUEUED', 'Queued'), ('RUNNING', 'Running'), ('SUCCEEDED', 'Succeeded'), ('FAILED', 'Failed'), ('CANCELED', 'Canceled')], default='RUNNING', max_length=16),
        ),
        migrations.AddIndex(
            model_name='reportrun',
            index=models.Index(fields=['company', 'status', 'priority', 'started_at'], name='ix_report_run_queue'),
        ),
        migrations.AddIndex(
            model_name='reportrun',
            index=models.Index(fields=['company', 'dedupe_key'], name='ix_report_run_dedupe'),
        ),
        migrations.AddField(
            model_name='datasetcache',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_dataset_cache', to='iam.orgunit'),
        ),
        migrations.AddField(
            model_name='datasetversion',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_dataset_versions', to='iam.orgunit'),
        ),
        migrations.AddField(
            model_name='reportexport',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_exports_approved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reportexport',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_exports', to='iam.orgunit'),
        ),
        migrations.AddField(
            model_name='reportexport',
            name='execution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exports', to='reports.reportrun'),
        ),
        migrations.AddField(
            model_name='reportexport',
            name='exported_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_exports_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reportreadaudit',
            name='actor_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_read_audits', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reportreadaudit',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_read_audits', to='iam.orgunit'),
        ),
        migrations.AddField(
            model_name='reportreadaudit',
            name='execution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='read_audits', to='reports.reportrun'),
        ),
        migrations.AddField(
            model_name='reproducibilityledger',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_repro_ledger', to='iam.orgunit'),
        ),
        migrations.AddField(
            model_name='reproducibilityledger',
            name='execution',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reproducibility_ledger', to='reports.reportrun'),
        ),
        migrations.AddField(
            model_name='reproducibilityledger',
            name='generated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_repro_ledger_generated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sourceregistry',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='report_sources', to='iam.orgunit'),
        ),
        migrations.AddIndex(
            model_name='datasetcache',
            index=models.Index(fields=['company', 'dataset_code', 'expires_at'], name='ix_dataset_cache_exp'),
        ),
        migrations.AddConstraint(
            model_name='datasetcache',
            constraint=models.UniqueConstraint(fields=('company', 'dataset_code', 'dataset_version', 'scope_hash', 'params_hash'), name='uniq_dataset_cache_key'),
        ),
        migrations.AddConstraint(
            model_name='datasetversion',
            constraint=models.UniqueConstraint(fields=('company', 'dataset_code', 'dataset_version'), name='uniq_dataset_version_per_company'),
        ),
        migrations.AddIndex(
            model_name='reportexport',
            index=models.Index(fields=['company', 'status', 'requested_at'], name='ix_report_export_queue'),
        ),
        migrations.AddIndex(
            model_name='reportreadaudit',
            index=models.Index(fields=['company', 'occurred_at'], name='ix_report_read_audit_time'),
        ),
        migrations.AddIndex(
            model_name='reportreadaudit',
            index=models.Index(fields=['company', 'report_code', 'occurred_at'], name='ix_report_read_audit_report'),
        ),
        migrations.AddIndex(
            model_name='sourceregistry',
            index=models.Index(fields=['source_type', 'status'], name='ix_report_source_type'),
        ),
        migrations.AddConstraint(
            model_name='sourceregistry',
            constraint=models.UniqueConstraint(fields=('company', 'source_code'), name='uniq_report_source_per_company'),
        ),
    ]
