# Generated by Django 5.2.9 on 2026-02-08 23:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("audit", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="auditevent",
            name="signature_key_id",
            field=models.CharField(blank=True, default="", max_length=32),
        ),
    ]
