# Generated by Django 5.2.9 on 2026-01-02 00:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone

class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("iam", "0001_initial"),
        ("rbac", "0002_roleassignment_origin"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="JobPosition",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("company", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="job_positions", to="iam.orgunit")),
                ("code", models.CharField(max_length=64, blank=True, default="")),
                ("name", models.CharField(max_length=200)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="PositionRoleMap",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("scope_mode", models.CharField(max_length=16, default="BRANCH")),
                ("is_active", models.BooleanField(default=True)),
                ("position", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="role_maps", to="hr.jobposition")),
                ("role", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="position_maps", to="rbac.role")),
            ],
        ),
        migrations.CreateModel(
            name="Employee",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("employee_code", models.CharField(max_length=64, blank=True, default="")),
                ("first_name", models.CharField(max_length=120)),
                ("last_name", models.CharField(max_length=120, blank=True, default="")),
                ("phone", models.CharField(max_length=64, blank=True, default="")),
                ("email", models.EmailField(blank=True, default="")),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("company", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="employees", to="iam.orgunit")),
                ("linked_user", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="employee_links", to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name="EmploymentAssignment",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("is_active", models.BooleanField(default=True)),
                ("started_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("ended_at", models.DateTimeField(null=True, blank=True)),
                ("employee", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="assignments", to="hr.employee")),
                ("position", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="assignments", to="hr.jobposition")),
                ("branch", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="employment_assignments", to="iam.orgunit")),
                ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="employment_assignments_created", to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name="jobposition",
            constraint=models.UniqueConstraint(fields=("company", "name"), name="uq_position_company_name"),
        ),
        migrations.AddConstraint(
            model_name="positionrolemap",
            constraint=models.UniqueConstraint(fields=("position", "role", "scope_mode"), name="uq_position_role_scope"),
        ),
        migrations.AddIndex(
            model_name="jobposition",
            index=models.Index(fields=["company", "is_active"], name="hr_jobposition_company_isactive_idx"),
        ),
        migrations.AddIndex(
            model_name="employee",
            index=models.Index(fields=["company", "is_active"], name="hr_employee_company_isactive_idx"),
        ),
        migrations.AddIndex(
            model_name="employee",
            index=models.Index(fields=["linked_user"], name="hr_employee_linked_user_idx"),
        ),
        migrations.AddIndex(
            model_name="positionrolemap",
            index=models.Index(fields=["position", "is_active"], name="hr_positionrolemap_position_isactive_idx"),
        ),
        migrations.AddIndex(
            model_name="employmentassignment",
            index=models.Index(fields=["employee", "is_active"], name="hr_employmentassignment_employee_isactive_idx"),
        ),
        migrations.AddIndex(
            model_name="employmentassignment",
            index=models.Index(fields=["position", "is_active"], name="hr_employmentassignment_position_isactive_idx"),
        ),
        migrations.AddIndex(
            model_name="employmentassignment",
            index=models.Index(fields=["branch", "is_active"], name="hr_employmentassignment_branch_isactive_idx"),
        ),
    ]
