# Generated by Django 5.2.9 on 2026-03-23 22:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0003_datasetcache_datasetversion_reportexport_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="reportdefinition",
            name="certification_status",
            field=models.CharField(
                choices=[("DRAFT", "Draft"), ("CERTIFIED", "Certified"), ("DEPRECATED", "Deprecated"), ("RETIRED", "Retired")],
                default="CERTIFIED",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="reportdefinition",
            name="dataset_key",
            field=models.CharField(blank=True, default="", max_length=128),
        ),
        migrations.AddField(
            model_name="reportdefinition",
            name="domain_owner",
            field=models.CharField(default="REPORTS", max_length=64),
        ),
        migrations.AddField(
            model_name="reportdefinition",
            name="export_capabilities",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="reportdefinition",
            name="freshness_mode",
            field=models.CharField(
                choices=[("live", "Live"), ("near_real_time", "Near Real Time"), ("snapshot", "Snapshot")],
                default="live",
                max_length=24,
            ),
        ),
        migrations.AddField(
            model_name="reportdefinition",
            name="materialization_policy",
            field=models.CharField(
                choices=[("live_only", "Live Only"), ("cache_first", "Cache First"), ("snapshot_required", "Snapshot Required")],
                default="cache_first",
                max_length=24,
            ),
        ),
        migrations.AddField(
            model_name="reportdefinition",
            name="required_permissions",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="reportdefinition",
            name="scope_level",
            field=models.CharField(
                choices=[("COMPANY", "Company"), ("BRANCH", "Branch"), ("INTERCOMPANY", "Intercompany")],
                default="BRANCH",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="reportdefinition",
            name="semantic_metric_keys",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="reportdefinition",
            name="semantic_version",
            field=models.CharField(default="1.0.0", max_length=32),
        ),
        migrations.AddField(
            model_name="reportrun",
            name="lineage",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name="ReportMetricDefinition",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("metric_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("metric_key", models.CharField(max_length=128)),
                ("name", models.CharField(max_length=160)),
                ("description", models.CharField(blank=True, default="", max_length=500)),
                ("domain_owner", models.CharField(default="REPORTS", max_length=64)),
                ("dataset_key", models.CharField(blank=True, default="", max_length=128)),
                ("expression", models.TextField(blank=True, default="")),
                ("expression_hash", models.CharField(blank=True, default="", max_length=64)),
                ("unit", models.CharField(blank=True, default="", max_length=24)),
                ("semantic_version", models.CharField(default="1.0.0", max_length=32)),
                ("formula_version", models.CharField(blank=True, default="", max_length=64)),
                ("status", models.CharField(choices=[("ACTIVE", "Active"), ("DEPRECATED", "Deprecated"), ("RETIRED", "Retired")], default="ACTIVE", max_length=16)),
                ("is_certified", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="report_metric_definitions",
                        to="iam.orgunit",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="reportmetricdefinition",
            constraint=models.UniqueConstraint(fields=("company", "metric_key"), name="uniq_report_metric_per_company"),
        ),
        migrations.AddIndex(
            model_name="reportmetricdefinition",
            index=models.Index(fields=["company", "domain_owner"], name="ix_report_metric_domain"),
        ),
        migrations.AddIndex(
            model_name="reportmetricdefinition",
            index=models.Index(fields=["company", "dataset_key"], name="ix_report_metric_dataset"),
        ),
    ]
