# Generated by Django 5.2.9 on 2026-03-07

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("iam", "0003_orgunit_parent_type_name_idx"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CashSession",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPEN", "Open"),
                            ("COUNT_PENDING", "Count pending"),
                            ("REVIEW_PENDING", "Review pending"),
                            ("CLOSED", "Closed"),
                            ("REOPENED_FOR_INVESTIGATION", "Reopened for investigation"),
                        ],
                        default="OPEN",
                        max_length=32,
                    ),
                ),
                ("opened_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                ("opening_amount", models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ("expected_amount", models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ("counted_amount", models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ("difference_amount", models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ("notes", models.TextField(blank=True, default="")),
                ("metadata", models.JSONField(default=dict)),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cash_sessions_branch",
                        to="iam.orgunit",
                    ),
                ),
                (
                    "closed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cash_sessions_closed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cash_sessions_company",
                        to="iam.orgunit",
                    ),
                ),
                (
                    "opened_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cash_sessions_opened",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PaymentIntent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("payment_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("external_ref", models.CharField(blank=True, default="", max_length=96)),
                ("idempotency_key", models.CharField(blank=True, default="", max_length=96)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=18)),
                ("currency", models.CharField(default="NIO", max_length=8)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("INTENDED", "Intended"),
                            ("AUTHORIZED", "Authorized"),
                            ("CAPTURED", "Captured"),
                            ("REFUNDED", "Refunded"),
                            ("FAILED", "Failed"),
                        ],
                        default="INTENDED",
                        max_length=16,
                    ),
                ),
                ("provider", models.CharField(blank=True, default="", max_length=32)),
                ("provider_txn_id", models.CharField(blank=True, default="", max_length=96)),
                ("authorized_at", models.DateTimeField(blank=True, null=True)),
                ("captured_at", models.DateTimeField(blank=True, null=True)),
                ("refunded_at", models.DateTimeField(blank=True, null=True)),
                ("failed_at", models.DateTimeField(blank=True, null=True)),
                ("failure_reason", models.CharField(blank=True, default="", max_length=255)),
                ("metadata", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pay_intents_branch",
                        to="iam.orgunit",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pay_intents_company",
                        to="iam.orgunit",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CashMovement",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "movement_type",
                    models.CharField(
                        choices=[
                            ("INCOME", "Income"),
                            ("EXPENSE", "Expense"),
                            ("ADJUSTMENT", "Adjustment"),
                            ("REFUND", "Refund"),
                        ],
                        max_length=16,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=18)),
                ("reference", models.CharField(blank=True, default="", max_length=96)),
                ("reason", models.CharField(blank=True, default="", max_length=255)),
                ("metadata", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cash_movements_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="movements",
                        to="payments.cashsession",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="paymentintent",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gt", 0)),
                name="ck_pay_intent_amount_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="paymentintent",
            constraint=models.UniqueConstraint(
                condition=models.Q(("idempotency_key", ""), _negated=True),
                fields=("company", "idempotency_key"),
                name="uq_pay_intent_company_idempotency",
            ),
        ),
        migrations.AddConstraint(
            model_name="cashmovement",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gt", 0)),
                name="ck_cash_movement_amount_positive",
            ),
        ),
        migrations.AddIndex(
            model_name="cashsession",
            index=models.Index(
                fields=["company", "branch", "status", "opened_at"],
                name="payments_ca_company_5f25f0_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="paymentintent",
            index=models.Index(
                fields=["company", "branch", "status", "created_at"],
                name="payments_pa_company_745d5f_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="paymentintent",
            index=models.Index(fields=["provider", "provider_txn_id"], name="payments_pa_provider_83867f_idx"),
        ),
        migrations.AddIndex(
            model_name="cashmovement",
            index=models.Index(fields=["session", "created_at"], name="payments_ca_session_80ee8d_idx"),
        ),
    ]
