# Generated by Django 5.2.9 on 2026-03-07

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("iam", "0003_orgunit_parent_type_name_idx"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EconomicEvent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("event_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("source_module", models.CharField(max_length=64)),
                ("event_type", models.CharField(max_length=128)),
                ("occurred_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("contract_version", models.CharField(default="1.0", max_length=16)),
                ("schema_version", models.PositiveSmallIntegerField(default=1)),
                ("correlation_id", models.CharField(blank=True, default="", max_length=96)),
                ("causation_id", models.CharField(blank=True, default="", max_length=96)),
                ("payload", models.JSONField(default=dict)),
                ("input_manifest_hash", models.CharField(blank=True, default="", max_length=64)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="acc_events_branch",
                        to="iam.orgunit",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="acc_events_company",
                        to="iam.orgunit",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FiscalPeriod",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("year", models.PositiveSmallIntegerField()),
                ("month", models.PositiveSmallIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[("OPEN", "Open"), ("CLOSED", "Closed")],
                        default="OPEN",
                        max_length=12,
                    ),
                ),
                ("opened_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "closed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="acc_periods_closed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="acc_periods_company",
                        to="iam.orgunit",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PostingRuleSet",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("code", models.CharField(max_length=64)),
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "status",
                    models.CharField(
                        choices=[("DRAFT", "Draft"), ("ACTIVE", "Active"), ("DEPRECATED", "Deprecated")],
                        default="DRAFT",
                        max_length=16,
                    ),
                ),
                (
                    "fiscal_mode",
                    models.CharField(
                        choices=[("A", "Fiscal A"), ("B", "Fiscal B"), ("BOTH", "Both")],
                        default="BOTH",
                        max_length=8,
                    ),
                ),
                ("jurisdiction", models.CharField(blank=True, default="", max_length=32)),
                ("effective_from", models.DateTimeField(blank=True, null=True)),
                ("effective_to", models.DateTimeField(blank=True, null=True)),
                ("rules_json", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "scope_company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="acc_posting_rules_company",
                        to="iam.orgunit",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="JournalDraft",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("GENERATED", "Generated"),
                            ("VALIDATED", "Validated"),
                            ("EXCEPTION", "Exception"),
                            ("APPROVED_FOR_POSTING", "Approved for posting"),
                            ("POSTED", "Posted"),
                            ("SUPERSEDED", "Superseded"),
                        ],
                        default="GENERATED",
                        max_length=24,
                    ),
                ),
                ("contract_version", models.CharField(default="1.0", max_length=16)),
                ("schema_version", models.PositiveSmallIntegerField(default=1)),
                ("close_run_id", models.CharField(blank=True, default="", max_length=64)),
                ("input_manifest_hash", models.CharField(blank=True, default="", max_length=64)),
                ("lines_json", models.JSONField(default=list)),
                ("total_debit", models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ("total_credit", models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ("generated_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("validated_at", models.DateTimeField(blank=True, null=True)),
                ("posted_at", models.DateTimeField(blank=True, null=True)),
                ("metadata", models.JSONField(default=dict)),
                (
                    "economic_event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="journal_drafts",
                        to="accounting.economicevent",
                    ),
                ),
                (
                    "rule_set",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="journal_drafts",
                        to="accounting.postingruleset",
                    ),
                ),
                (
                    "superseded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="supersedes",
                        to="accounting.journaldraft",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="JournalEntry",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("entry_date", models.DateField(default=django.utils.timezone.localdate)),
                ("description", models.CharField(blank=True, default="", max_length=255)),
                ("debit_total", models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ("credit_total", models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ("is_posted", models.BooleanField(default=True)),
                ("posted_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("metadata", models.JSONField(default=dict)),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="journal_entries_branch",
                        to="iam.orgunit",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="journal_entries_company",
                        to="iam.orgunit",
                    ),
                ),
                (
                    "draft",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="journal_entry",
                        to="accounting.journaldraft",
                    ),
                ),
                (
                    "period",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="journal_entries",
                        to="accounting.fiscalperiod",
                    ),
                ),
                (
                    "reversed_entry",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reverses",
                        to="accounting.journalentry",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="fiscalperiod",
            constraint=models.UniqueConstraint(
                fields=("company", "year", "month"),
                name="uq_acc_period_company_year_month",
            ),
        ),
        migrations.AddConstraint(
            model_name="fiscalperiod",
            constraint=models.CheckConstraint(
                condition=models.Q(("month__gte", 1), ("month__lte", 12)),
                name="ck_acc_period_month_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="postingruleset",
            constraint=models.UniqueConstraint(fields=("code", "version"), name="uq_acc_posting_rule_code_version"),
        ),
        migrations.AddConstraint(
            model_name="journaldraft",
            constraint=models.CheckConstraint(
                condition=models.Q(("total_debit__gte", 0)),
                name="ck_acc_jdraft_debit_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="journaldraft",
            constraint=models.CheckConstraint(
                condition=models.Q(("total_credit__gte", 0)),
                name="ck_acc_jdraft_credit_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="journalentry",
            constraint=models.CheckConstraint(
                condition=models.Q(("debit_total__gte", 0)),
                name="ck_acc_jentry_debit_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="journalentry",
            constraint=models.CheckConstraint(
                condition=models.Q(("credit_total__gte", 0)),
                name="ck_acc_jentry_credit_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="journalentry",
            constraint=models.CheckConstraint(
                condition=models.Q(("debit_total", models.F("credit_total"))),
                name="ck_acc_jentry_balanced",
            ),
        ),
        migrations.AddIndex(
            model_name="economicevent",
            index=models.Index(
                fields=["company", "branch", "occurred_at"],
                name="accounting_e_company_f49629_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="economicevent",
            index=models.Index(
                fields=["source_module", "event_type", "occurred_at"],
                name="accounting_e_source__6b8e4b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="fiscalperiod",
            index=models.Index(fields=["company", "year", "month"], name="accounting_f_company_82731e_idx"),
        ),
        migrations.AddIndex(
            model_name="fiscalperiod",
            index=models.Index(fields=["company", "status"], name="accounting_f_company_6b9dd0_idx"),
        ),
        migrations.AddIndex(
            model_name="postingruleset",
            index=models.Index(fields=["status", "fiscal_mode"], name="accounting_p_status_39f893_idx"),
        ),
        migrations.AddIndex(
            model_name="postingruleset",
            index=models.Index(fields=["scope_company", "status"], name="accounting_p_scope_c2849c_idx"),
        ),
        migrations.AddIndex(
            model_name="journaldraft",
            index=models.Index(fields=["state", "generated_at"], name="accounting_j_state_7f2d87_idx"),
        ),
        migrations.AddIndex(
            model_name="journaldraft",
            index=models.Index(fields=["economic_event", "state"], name="accounting_j_economi_0f6dfe_idx"),
        ),
        migrations.AddIndex(
            model_name="journalentry",
            index=models.Index(fields=["company", "period", "entry_date"], name="accounting_j_company_0ce87b_idx"),
        ),
        migrations.AddIndex(
            model_name="journalentry",
            index=models.Index(fields=["period", "is_posted"], name="accounting_j_period_b6a017_idx"),
        ),
    ]
