# Generated by Django 5.2.9 on 2026-03-08

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cec", "0002_phase3_fields"),
        ("accounting", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="economicevent",
            name="close_run_id",
            field=models.CharField(blank=True, db_index=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="economicevent",
            name="source_outbox_event_id",
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddConstraint(
            model_name="economicevent",
            constraint=models.UniqueConstraint(
                condition=models.Q(source_outbox_event_id__isnull=False),
                fields=("company", "source_outbox_event_id"),
                name="uq_acc_event_company_source_outbox",
            ),
        ),
        migrations.AddIndex(
            model_name="economicevent",
            index=models.Index(
                fields=["company", "close_run_id", "occurred_at"],
                name="acc_ev_company_run_occ_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="journaldraft",
            constraint=models.UniqueConstraint(
                fields=("economic_event", "rule_set"),
                name="uq_acc_jdraft_event_rule_set",
            ),
        ),
        migrations.CreateModel(
            name="DraftValidationResult",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("passed", models.BooleanField(default=False)),
                ("errors_json", models.JSONField(default=list)),
                ("is_blocking", models.BooleanField(default=True)),
                ("validated_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                (
                    "draft",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="validation_result",
                        to="accounting.journaldraft",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["passed", "is_blocking", "validated_at"],
                        name="acc_dval_pass_block_val_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ExceptionLink",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                (
                    "draft",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="exception_links",
                        to="accounting.journaldraft",
                    ),
                ),
                (
                    "exception",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="accounting_exception_links",
                        to="cec.cecexception",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["exception", "created_at"], name="acc_exlink_exc_created_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("draft", "exception"),
                        name="uq_acc_exception_link_draft_exception",
                    )
                ],
            },
        ),
    ]
