# Generated by Codex on 2026-03-08

import decimal
import uuid

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounting", "0003_phase5_sod_actor_trace"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ChartOfAccount",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("code", models.CharField(max_length=32)),
                ("name", models.CharField(max_length=128)),
                (
                    "account_type",
                    models.CharField(
                        choices=[
                            ("ASSET", "Asset"),
                            ("LIABILITY", "Liability"),
                            ("EQUITY", "Equity"),
                            ("REVENUE", "Revenue"),
                            ("EXPENSE", "Expense"),
                        ],
                        max_length=16,
                    ),
                ),
                ("is_postable", models.BooleanField(default=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_revaluable", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="acc_chart_accounts",
                        to="iam.orgunit",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="children",
                        to="accounting.chartofaccount",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["company", "account_type", "is_active"], name="acc_coa_comp_type_act_idx"),
                    models.Index(fields=["company", "is_postable", "is_active"], name="acc_coa_comp_post_act_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(fields=("company", "code"), name="uq_acc_coa_company_code"),
                ],
            },
        ),
        migrations.CreateModel(
            name="FxRate",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("rate_date", models.DateField()),
                ("from_currency", models.CharField(max_length=8)),
                ("to_currency", models.CharField(max_length=8)),
                ("rate_type", models.CharField(choices=[("CLOSING", "Closing"), ("SPOT", "Spot"), ("AVERAGE", "Average")], default="CLOSING", max_length=16)),
                ("rate", models.DecimalField(decimal_places=8, max_digits=18)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="acc_fx_rates",
                        to="iam.orgunit",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["company", "rate_type", "rate_date"], name="acc_fx_comp_type_date_idx"),
                    models.Index(
                        fields=["company", "from_currency", "to_currency", "rate_date"],
                        name="acc_fx_comp_pair_date_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("company", "rate_date", "from_currency", "to_currency", "rate_type"),
                        name="uq_acc_fx_rate_scope",
                    ),
                    models.CheckConstraint(condition=models.Q(rate__gt=0), name="ck_acc_fx_rate_positive"),
                ],
            },
        ),
        migrations.CreateModel(
            name="RevaluationRun",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("run_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("year", models.PositiveSmallIntegerField()),
                ("month", models.PositiveSmallIntegerField()),
                ("scope_hash", models.CharField(max_length=64)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("RUNNING", "Running"),
                            ("COMPLETED", "Completed"),
                            ("BLOCKED", "Blocked"),
                            ("FAILED", "Failed"),
                        ],
                        default="RUNNING",
                        max_length=16,
                    ),
                ),
                ("summary_json", models.JSONField(default=dict)),
                ("executed_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="acc_revaluation_runs",
                        to="iam.orgunit",
                    ),
                ),
                (
                    "executed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="acc_revaluation_runs_executed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["company", "year", "month", "status"], name="acc_reval_comp_ym_stat_idx"),
                    models.Index(fields=["company", "status", "executed_at"], name="acc_reval_comp_stat_exec_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("company", "year", "month", "scope_hash"),
                        name="uq_acc_revaluation_company_period_scope",
                    ),
                    models.CheckConstraint(condition=models.Q(month__gte=1, month__lte=12), name="ck_acc_revaluation_month_range"),
                ],
            },
        ),
        migrations.CreateModel(
            name="CompanyAccountingConfig",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("functional_currency", models.CharField(default="NIO", max_length=8)),
                ("phase7_enabled", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="accounting_config",
                        to="iam.orgunit",
                    ),
                ),
                (
                    "fx_gain_account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="configured_as_fx_gain",
                        to="accounting.chartofaccount",
                    ),
                ),
                (
                    "fx_loss_account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="configured_as_fx_loss",
                        to="accounting.chartofaccount",
                    ),
                ),
                (
                    "retained_earnings_account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="configured_as_retained_earnings",
                        to="accounting.chartofaccount",
                    ),
                ),
            ],
            options={
                "indexes": [models.Index(fields=["phase7_enabled"], name="acc_cfg_phase7_idx")],
            },
        ),
        migrations.CreateModel(
            name="JournalEntryLine",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("line_no", models.PositiveIntegerField()),
                ("account_code_snapshot", models.CharField(max_length=32)),
                ("currency", models.CharField(default="NIO", max_length=8)),
                ("fx_rate", models.DecimalField(decimal_places=8, default=decimal.Decimal("1.00000000"), max_digits=18)),
                ("amount_tx", models.DecimalField(decimal_places=2, default=decimal.Decimal("0.00"), max_digits=18)),
                ("debit_base", models.DecimalField(decimal_places=2, default=decimal.Decimal("0.00"), max_digits=18)),
                ("credit_base", models.DecimalField(decimal_places=2, default=decimal.Decimal("0.00"), max_digits=18)),
                ("meta_json", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="journal_entry_lines",
                        to="accounting.chartofaccount",
                    ),
                ),
                (
                    "journal_entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lines",
                        to="accounting.journalentry",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["journal_entry", "line_no"], name="acc_jline_entry_line_idx"),
                    models.Index(fields=["account", "created_at"], name="acc_jline_account_created_idx"),
                    models.Index(fields=["currency", "created_at"], name="acc_jline_currency_created_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(fields=("journal_entry", "line_no"), name="uq_acc_jentry_line_order"),
                    models.CheckConstraint(condition=models.Q(fx_rate__gt=0), name="ck_acc_jline_fx_rate_positive"),
                    models.CheckConstraint(condition=models.Q(debit_base__gte=0), name="ck_acc_jline_debit_non_negative"),
                    models.CheckConstraint(condition=models.Q(credit_base__gte=0), name="ck_acc_jline_credit_non_negative"),
                ],
            },
        ),
        migrations.CreateModel(
            name="RevaluationEntryLink",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                (
                    "journal_entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="revaluation_links",
                        to="accounting.journalentry",
                    ),
                ),
                (
                    "revaluation_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="entry_links",
                        to="accounting.revaluationrun",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["journal_entry", "created_at"], name="acc_reval_link_entry_created_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("revaluation_run", "journal_entry"),
                        name="uq_acc_revaluation_entry_link",
                    )
                ],
            },
        ),
    ]
