# Generated by Codex on 2026-03-08

import decimal
import uuid

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounting", "0004_phase7a_gl_core"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ConsolidationRun",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("run_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("year", models.PositiveSmallIntegerField()),
                ("month", models.PositiveSmallIntegerField()),
                ("scope_hash", models.CharField(max_length=64)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("RUNNING", "Running"),
                            ("COMPLETED", "Completed"),
                            ("BLOCKED", "Blocked"),
                            ("FAILED", "Failed"),
                        ],
                        default="RUNNING",
                        max_length=16,
                    ),
                ),
                ("company_ids_json", models.JSONField(default=list)),
                ("summary_json", models.JSONField(default=dict)),
                ("input_manifest_hash", models.CharField(blank=True, default="", max_length=64)),
                ("output_manifest_hash", models.CharField(blank=True, default="", max_length=64)),
                ("started_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "executed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="acc_consolidation_runs_executed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "parent_company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="acc_consolidation_runs_parent",
                        to="iam.orgunit",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["parent_company", "year", "month", "status"], name="acc_cons_comp_ym_stat_idx"),
                    models.Index(fields=["status", "started_at"], name="acc_cons_stat_start_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("parent_company", "year", "month", "scope_hash"),
                        name="uq_acc_consolidation_scope",
                    ),
                    models.CheckConstraint(condition=models.Q(month__gte=1, month__lte=12), name="ck_acc_consolidation_month_range"),
                ],
            },
        ),
        migrations.CreateModel(
            name="IntercompanyTransaction",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("tx_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("CONFIRMED", "Confirmed"),
                            ("DIFFERENCE", "Difference"),
                            ("DISPUTED", "Disputed"),
                            ("CLOSED", "Closed"),
                        ],
                        default="PENDING",
                        max_length=16,
                    ),
                ),
                ("reference_code", models.CharField(blank=True, default="", max_length=96)),
                ("currency", models.CharField(default="NIO", max_length=8)),
                ("amount", models.DecimalField(decimal_places=2, default=decimal.Decimal("0.00"), max_digits=18)),
                ("source_account_code", models.CharField(blank=True, default="", max_length=32)),
                ("target_account_code", models.CharField(blank=True, default="", max_length=32)),
                (
                    "source_side",
                    models.CharField(choices=[("DEBIT", "Debit"), ("CREDIT", "Credit")], default="CREDIT", max_length=8),
                ),
                (
                    "target_side",
                    models.CharField(choices=[("DEBIT", "Debit"), ("CREDIT", "Credit")], default="DEBIT", max_length=8),
                ),
                ("matched_amount_source", models.DecimalField(decimal_places=2, default=decimal.Decimal("0.00"), max_digits=18)),
                ("matched_amount_target", models.DecimalField(decimal_places=2, default=decimal.Decimal("0.00"), max_digits=18)),
                ("difference_amount", models.DecimalField(decimal_places=2, default=decimal.Decimal("0.00"), max_digits=18)),
                ("description", models.CharField(blank=True, default="", max_length=255)),
                ("metadata_json", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "closed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="acc_intercompany_transactions_closed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "confirmed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="acc_intercompany_transactions_confirmed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="acc_intercompany_transactions_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "source_company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="acc_intercompany_source_transactions",
                        to="iam.orgunit",
                    ),
                ),
                (
                    "source_journal_entry",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="acc_intercompany_source_journal_transactions",
                        to="accounting.journalentry",
                    ),
                ),
                (
                    "target_company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="acc_intercompany_target_transactions",
                        to="iam.orgunit",
                    ),
                ),
                (
                    "target_journal_entry",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="acc_intercompany_target_journal_transactions",
                        to="accounting.journalentry",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["source_company", "target_company", "status", "created_at"], name="acc_ic_tx_scope_stat_idx"),
                    models.Index(fields=["status", "created_at"], name="acc_ic_tx_stat_created_idx"),
                    models.Index(fields=["reference_code"], name="acc_ic_tx_ref_idx"),
                ],
                "constraints": [
                    models.CheckConstraint(condition=~models.Q(source_company=models.F("target_company")), name="ck_acc_ic_tx_company_distinct"),
                    models.CheckConstraint(condition=models.Q(amount__gt=0), name="ck_acc_ic_tx_amount_positive"),
                ],
            },
        ),
        migrations.CreateModel(
            name="IntercompanyReconciliation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("CONFIRMED", "Confirmed"),
                            ("DIFFERENCE", "Difference"),
                            ("DISPUTED", "Disputed"),
                            ("CLOSED", "Closed"),
                        ],
                        default="PENDING",
                        max_length=16,
                    ),
                ),
                ("source_amount", models.DecimalField(decimal_places=2, default=decimal.Decimal("0.00"), max_digits=18)),
                ("target_amount", models.DecimalField(decimal_places=2, default=decimal.Decimal("0.00"), max_digits=18)),
                ("difference_amount", models.DecimalField(decimal_places=2, default=decimal.Decimal("0.00"), max_digits=18)),
                ("note", models.CharField(blank=True, default="", max_length=255)),
                ("details_json", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="acc_intercompany_reconciliations_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "transaction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reconciliations",
                        to="accounting.intercompanytransaction",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["transaction", "status", "created_at"], name="acc_ic_rec_tx_stat_idx"),
                    models.Index(fields=["status", "created_at"], name="acc_ic_rec_stat_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="ConsolidationEliminationLink",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("elimination_json", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                (
                    "consolidation_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="elimination_links",
                        to="accounting.consolidationrun",
                    ),
                ),
                (
                    "intercompany_transaction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="consolidation_links",
                        to="accounting.intercompanytransaction",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["consolidation_run", "created_at"], name="acc_cons_elim_run_idx"),
                    models.Index(fields=["intercompany_transaction", "created_at"], name="acc_cons_elim_tx_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("consolidation_run", "intercompany_transaction"),
                        name="uq_acc_consolidation_elimination_link",
                    ),
                ],
            },
        ),
    ]
