# Generated by Django 5.2.9 on 2026-01-02 00:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rbac", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="roleassignment",
            name="origin",
            field=models.CharField(
                max_length=16,
                choices=[("MANUAL", "Manual"), ("POSITION", "Position automation"), ("SYSTEM", "System bootstrap")],
                default="MANUAL",
            ),
        ),
        migrations.AddField(
            model_name="roleassignment",
            name="origin_ref",
            field=models.CharField(blank=True, default="", max_length=128),
        ),
        migrations.RemoveConstraint(
            model_name="roleassignment",
            name="uq_roleassignment_user_role_orgunit",
        ),
        migrations.AddConstraint(
            model_name="roleassignment",
            constraint=models.UniqueConstraint(
                fields=["user", "role", "org_unit", "origin"],
                name="uq_roleassignment_user_role_orgunit_origin",
            ),
        ),
        migrations.AddIndex(
            model_name="roleassignment",
            index=models.Index(fields=["origin", "is_active"], name="rbac_roleas_origin_isactive_idx"),
        ),
    ]
