# Generated by Django 5.2.9 on 2025-12-31 21:31

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("iam", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Device",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("label", models.CharField(blank=True, default="", max_length=200)),
                (
                    "status",
                    models.CharField(
                        choices=[("ACTIVE", "Active"), ("REVOKED", "Revoked"), ("QUARANTINED", "Quarantined")],
                        default="ACTIVE",
                        max_length=16,
                    ),
                ),
                ("public_key", models.BinaryField(max_length=64)),
                ("min_app_version", models.CharField(blank=True, default="", max_length=32)),
                ("meta", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                ("last_seen_at", models.DateTimeField(blank=True, null=True)),
                ("last_accepted_sequence", models.BigIntegerField(default=0)),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"unit_type": "BRANCH"},
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="devices_branch",
                        to="iam.orgunit",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        limit_choices_to={"unit_type": "COMPANY"},
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="devices_company",
                        to="iam.orgunit",
                    ),
                ),
                (
                    "enrolled_by_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="enrolled_devices",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AppliedCommand",
            fields=[
                ("command_id", models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ("command_type", models.CharField(max_length=64)),
                ("occurred_at", models.DateTimeField(blank=True, null=True)),
                ("received_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("applied_at", models.DateTimeField(blank=True, null=True)),
                ("sequence", models.BigIntegerField(blank=True, null=True)),
                ("payload_hash", models.CharField(max_length=64)),
                ("prev_hash", models.CharField(blank=True, default="", max_length=64)),
                (
                    "result_status",
                    models.CharField(
                        choices=[("APPLIED", "Applied"), ("REJECTED", "Rejected"), ("DUPLICATE", "Duplicate")],
                        max_length=16,
                    ),
                ),
                ("result_ref", models.JSONField(blank=True, default=dict)),
                ("error", models.JSONField(blank=True, default=dict)),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"unit_type": "BRANCH"},
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="applied_commands_branch",
                        to="iam.orgunit",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        limit_choices_to={"unit_type": "COMPANY"},
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="applied_commands_company",
                        to="iam.orgunit",
                    ),
                ),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="applied_commands",
                        to="sync_engine.device",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DeviceEnrollmentChallenge",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("enrollment_code_hash", models.CharField(max_length=64, unique=True)),
                ("expires_at", models.DateTimeField()),
                ("used_at", models.DateTimeField(blank=True, null=True)),
                ("label_hint", models.CharField(blank=True, default="", max_length=200)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"unit_type": "BRANCH"},
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="device_enroll_challenges_branch",
                        to="iam.orgunit",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        limit_choices_to={"unit_type": "COMPANY"},
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="device_enroll_challenges_company",
                        to="iam.orgunit",
                    ),
                ),
                (
                    "created_by_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_device_enroll_challenges",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "used_by_device",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="used_challenges",
                        to="sync_engine.device",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SyncReceipt",
            fields=[
                ("batch_id", models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ("server_time", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("received_count", models.PositiveIntegerField(default=0)),
                ("applied_count", models.PositiveIntegerField(default=0)),
                ("rejected_count", models.PositiveIntegerField(default=0)),
                ("duplicate_count", models.PositiveIntegerField(default=0)),
                ("errors_summary", models.JSONField(blank=True, default=dict)),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sync_receipts",
                        to="sync_engine.device",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="device",
            index=models.Index(fields=["company", "status"], name="sync_engine_company_402270_idx"),
        ),
        migrations.AddIndex(
            model_name="device",
            index=models.Index(fields=["branch", "status"], name="sync_engine_branch__748124_idx"),
        ),
        migrations.AddIndex(
            model_name="device",
            index=models.Index(fields=["status", "last_seen_at"], name="sync_engine_status_cf5f57_idx"),
        ),
        migrations.AddIndex(
            model_name="appliedcommand",
            index=models.Index(fields=["device", "received_at"], name="sync_engine_device__baf559_idx"),
        ),
        migrations.AddIndex(
            model_name="appliedcommand",
            index=models.Index(fields=["company", "received_at"], name="sync_engine_company_a23787_idx"),
        ),
        migrations.AddIndex(
            model_name="appliedcommand",
            index=models.Index(fields=["result_status", "received_at"], name="sync_engine_result__fda575_idx"),
        ),
        migrations.AddIndex(
            model_name="appliedcommand",
            index=models.Index(fields=["command_type"], name="sync_engine_command_9cdeb7_idx"),
        ),
        migrations.AddIndex(
            model_name="deviceenrollmentchallenge",
            index=models.Index(fields=["company", "expires_at"], name="sync_engine_company_d85c95_idx"),
        ),
        migrations.AddIndex(
            model_name="deviceenrollmentchallenge",
            index=models.Index(fields=["used_at"], name="sync_engine_used_at_550e7a_idx"),
        ),
        migrations.AddIndex(
            model_name="syncreceipt",
            index=models.Index(fields=["device", "server_time"], name="sync_engine_device__a92bab_idx"),
        ),
    ]
