# Generated by Copilot on 2026-01-23

from __future__ import annotations

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("iam", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FuelShift",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "status",
                    models.CharField(
                        choices=[("OPEN", "Abierto"), ("CLOSED", "Cerrado")],
                        default="OPEN",
                        max_length=16,
                    ),
                ),
                ("opened_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                ("note", models.CharField(blank=True, default="", max_length=255)),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="fuel_shifts_branch",
                        to="iam.orgunit",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="fuel_shifts_company",
                        to="iam.orgunit",
                    ),
                ),
                (
                    "opened_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="fuel_shifts_opened",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "closed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="fuel_shifts_closed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [models.Index(fields=["company", "branch", "status", "opened_at"], name="estacion_se_company__7aa2c2_idx")],
            },
        ),
        migrations.CreateModel(
            name="FuelDispense",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("occurred_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("product", models.CharField(choices=[("DIESEL", "Diesel"), ("GASOLINE", "Gasolina")], max_length=16)),
                ("liters", models.DecimalField(decimal_places=3, max_digits=12)),
                ("unit_price", models.DecimalField(decimal_places=4, max_digits=12)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=14)),
                ("vehicle_plate", models.CharField(blank=True, default="", max_length=32)),
                ("vehicle_ref", models.CharField(blank=True, default="", max_length=64)),
                ("driver_name", models.CharField(blank=True, default="", max_length=120)),
                ("pump_code", models.CharField(blank=True, default="", max_length=32)),
                ("nozzle_code", models.CharField(blank=True, default="", max_length=32)),
                ("meter_reading", models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True)),
                ("external_ref", models.CharField(blank=True, default="", max_length=64)),
                ("note", models.CharField(blank=True, default="", max_length=255)),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="fuel_dispenses_branch",
                        to="iam.orgunit",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="fuel_dispenses_company",
                        to="iam.orgunit",
                    ),
                ),
                (
                    "recorded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="fuel_dispenses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "shift",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="dispenses",
                        to="estacion_servicios.fuelshift",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["company", "branch", "occurred_at"], name="estacion_se_company__c8e61a_idx"),
                    models.Index(fields=["shift", "occurred_at"], name="estacion_se_shift_i_2b6c2f_idx"),
                    models.Index(fields=["product", "occurred_at"], name="estacion_se_product_4fd987_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="FuelSale",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "sale_type",
                    models.CharField(
                        choices=[
                            ("INTERNAL", "Consumo interno"),
                            ("PUBLIC", "Venta al público"),
                            ("EMPLOYEE", "Empleado (crédito/abonos)"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[("CASH", "Efectivo"), ("TRANSFER", "Transferencia"), ("CREDIT", "Crédito")],
                        max_length=16,
                    ),
                ),
                ("customer_name", models.CharField(blank=True, default="", max_length=200)),
                ("customer_ref", models.CharField(blank=True, default="", max_length=64)),
                ("total_amount", models.DecimalField(decimal_places=2, max_digits=14)),
                (
                    "status",
                    models.CharField(
                        choices=[("ACTIVE", "Activa"), ("CANCELLED", "Anulada")],
                        default="ACTIVE",
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                ("cancel_reason", models.CharField(blank=True, default="", max_length=255)),
                ("is_fiscal", models.BooleanField(default=False)),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="fuel_sales_branch",
                        to="iam.orgunit",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="fuel_sales_company",
                        to="iam.orgunit",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="fuel_sales_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "cancelled_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="fuel_sales_cancelled",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "dispense",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sale",
                        to="estacion_servicios.fueldispense",
                    ),
                ),
                (
                    "shift",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sales",
                        to="estacion_servicios.fuelshift",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["company", "branch", "created_at"], name="estacion_se_company__8d6f1d_idx"),
                    models.Index(fields=["status", "created_at"], name="estacion_se_status__aeb1f0_idx"),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="fuelshift",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "OPEN")),
                fields=("branch",),
                name="uniq_open_shift_per_branch",
            ),
        ),
    ]
